storage: ../.local-registry/storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m
    cache: false

packages:
  "@gtkx/*":
    access: $all
    publish: $all
    unpublish: $all
  "create-gtkx":
    access: $all
    publish: $all
    unpublish: $all
  "@*/*":
    access: $all
    publish: $all
    proxy: npmjs
  "**":
    access: $all
    publish: $all
    proxy: npmjs

log:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true
