import "./bootstrap.js";

export { animated, type Animated } from "./animated.js";
export { useReducedMotion } from "./reduced-motion.js";
export type {
    AnimatedComponent,
    AnimatedElementMap,
    /* eslint-disable-next-line @typescript-eslint/no-deprecated -- exported until 2.0 removes it */
    AnimatedElements,
    AnimatedItems,
    AnimatedProp,
    AnimatedProps,
    AnimatedStyle,
} from "./types.js";
export {
    BailSignal,
    config,
    Controller,
    createInterpolator,
    easings,
    FrameValue,
    Globals,
    inferTo,
    Interpolation,
    Spring,
    SpringContext,
    SpringRef,
    SpringValue,
    to,
    Trail,
    Transition,
    update,
    useChain,
    useSpring,
    useSpringRef,
    useSprings,
    useSpringValue,
    useTrail,
    useTransition,
} from "@react-spring/core";
export type {
    AnimationConfig,
    AnimationProps,
    AnimationResult,
    AsyncResult,
    Change,
    ControllerFlushFn,
    ControllerProps,
    ControllerUpdate,
    EventProp,
    ForwardProps,
    GoalProp,
    GoalValue,
    GoalValues,
    InferTo,
    InlineToProps,
    Interpolated,
    Interpolator,
    ItemKeys,
    LoopProp,
    MatchProp,
    OnChange,
    OnPause,
    OnProps,
    OnResolve,
    OnRest,
    OnResume,
    OnStart,
    PickAnimated,
    ReservedEventProps,
    ReservedProps,
    SpringChain,
    SpringComponentProps,
    SpringConfig,
    SpringProps,
    SpringsUpdate,
    SpringTo,
    SpringToFn,
    SpringUpdate,
    SpringUpdateFn,
    SpringValues,
    Springify,
    ToProps,
    ToValues,
    TrailComponentProps,
    TransitionComponentProps,
    TransitionFn,
    TransitionFrom,
    TransitionKey,
    TransitionRenderFn,
    TransitionState,
    TransitionTo,
    TransitionValues,
    UseSpringProps,
    UseSpringsProps,
    UseTrailProps,
    UseTransitionProps,
    VelocityProp,
} from "@react-spring/core";
export type { FluidValue } from "@react-spring/shared";
export type {
    Animatable,
    EasingFunction,
    ExtrapolateType,
    InterpolatorArgs,
    InterpolatorConfig,
    InterpolatorFactory,
    InterpolatorFn,
    Lookup,
    OneOrMore,
    UnknownProps,
} from "@react-spring/types";
