paths:
  .github/workflows/publish.yml:
    ignore:
      - '^unexpected key "queue" for "concurrency" section\.'
  .github/workflows/tag-release.yml:
    ignore:
      - '^unexpected key "queue" for "concurrency" section\.'
