version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      workspace-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/examples/tutorial"
    schedule:
      interval: "daily"
    groups:
      tutorial-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "cargo"
    directory: "/packages/native"
    schedule:
      interval: "daily"
    groups:
      native-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "daily"
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/.github/docker"
    schedule:
      interval: "daily"
