packages:
  - .
  - packages/*
  - scripts
  - examples/*
  - "!examples/tutorial"
  - website

minimumReleaseAge: 0
trustPolicy: no-downgrade

verifyDepsBeforeRun: false

publicHoistPattern:
  - clipanion

trustPolicyExclude:
  - pino@9.14.0
  - semver@6.3.1

catalog:
  '@types/ejs': ^3.1.5
  '@types/node': ^26.4.0
  '@types/react': ^19.2.18
  '@vitest/coverage-v8': ^4.1.11
  ejs: ^6.0.1
  react: ^19.2.8
  typescript: ^6.0.3
  vite: ^8.2.2
  vitest: ^4.1.11
  yaml: ^2.9.0
  zod: ^4.5.4

allowBuilds:
  '@swc/core': true
  esbuild: true
  nx: true

packageExtensions:
  '@emotion/utils':
    dependencies:
      '@emotion/sheet': ^1.4.0

peerDependencyRules:
  allowedVersions:
    '@napi-rs/cli>@emnapi/runtime': '*'

overrides:
  vite: ^8.2.2
  qs: ^6.16.0
  axios: ^1.20.0
  brace-expansion: ^5.0.9

patchedDependencies:
  '@react-navigation/core@7.21.13': patches/@react-navigation__core@7.21.13.patch
  '@react-navigation/routers@7.6.4': patches/@react-navigation__routers@7.6.4.patch
  '@types/react-reconciler@0.33.0': patches/@types__react-reconciler@0.33.0.patch
