packages:
  - .
  - packages/*
  - packages/native/npm/*
  - examples/*
  - website

minimumReleaseAge: 0

allowBuilds:
  '@swc/core': true
  esbuild: true

patchedDependencies:
  typescript@6.0.3: patches/typescript@6.0.3.patch

overrides:
  '@docsearch/css': ^3.9.0
  '@docsearch/js': ^3.9.0
  '@docsearch/react': ^3.9.0
  qs: ^6.15.2
  uuid: ^11.1.1
