sonar.projectKey=gtkx-org_gtkx
sonar.organization=gtkx-org
sonar.scm.provider=git

sonar.sources=packages
sonar.tests=packages
sonar.test.inclusions=**/tests/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/dist/**,**/out-tsc/**,**/node_modules/**,**/target/**,**/.turbo/**,**/*.node

sonar.coverage.exclusions=packages/*/bin/**,packages/vitest/src/**,packages/codegen/overrides/**,packages/gl/src/generated/**,packages/*/scripts/**
sonar.cpd.exclusions=packages/codegen/overrides/**

sonar.issue.ignore.multicriteria=pkgConfigPathLookup
sonar.issue.ignore.multicriteria.pkgConfigPathLookup.ruleKey=typescript:S4036
sonar.issue.ignore.multicriteria.pkgConfigPathLookup.resourceKey=packages/codegen/src/gir/gir-path.ts

sonar.typescript.tsconfigPaths=tsconfig.json
sonar.javascript.node.maxspace=8192
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage/subprocess-report/lcov.info
