sonar.projectKey=gtkx-org_gtkx
sonar.organization=gtkx-org
sonar.projectName=gtkx

sonar.sources=packages
sonar.tests=packages
sonar.test.inclusions=**/tests/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/generated/**,**/dist/**,**/out-tsc/**,**/node_modules/**,**/target/**,**/.turbo/**,**/index.node,**/girs/**

sonar.coverage.exclusions=packages/*/bin/**,packages/vitest/src/**,packages/ffi/src/cairo/**,packages/cli/src/mcp-client.ts

sonar.typescript.tsconfigPaths=tsconfig.base.json
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=packages/cli/coverage/lcov.info,packages/codegen/coverage/lcov.info,packages/css/coverage/lcov.info,packages/e2e/coverage/lcov.info,packages/ffi/coverage/lcov.info,packages/gir/coverage/lcov.info,packages/mcp/coverage/lcov.info,packages/native/coverage/lcov.info,packages/testing/coverage/lcov.info
sonar.coverage.lcov.reportPaths=packages/native/coverage/native.lcov.info
