const APPLICATION_ID_PATTERN = /^[A-Za-z_][A-Za-z0-9_-]*(\.[A-Za-z_][A-Za-z0-9_-]*)+$/;
const APPLICATION_ID_MAX_LENGTH = 255;

/**
 * Validate a GTK application ID (a GApplication-style reverse-DNS identifier,
 * e.g. `com.example.MyApp`). Returns `true` when the value is a non-empty,
 * dot-separated identifier no longer than 255 characters whose every segment
 * starts with a letter or underscore.
 */
export const isValidApplicationId = (applicationId: string): boolean => {
    if (applicationId.length === 0 || applicationId.length > APPLICATION_ID_MAX_LENGTH) {
        return false;
    }
    return APPLICATION_ID_PATTERN.test(applicationId);
};

/**
 * Doc-comment header for the generated `node_modules/.gtkx/env.d.ts` ambient
 * module that declares a project's GSettings schema types. The codegen writes
 * this header above the per-schema declarations; the scaffolder writes it on
 * its own to seed an initial, schema-free env module.
 */
export const GTKX_ENV_MODULE_HEADER: string = `/**
 * GSettings schema modules generated by GTKX from the project's
 * \`.gschema.xml\` files. Regenerated by \`gtkx codegen\`, \`gtkx dev\`, and
 * \`gtkx build\`; do not edit.
 */`;

/**
 * Render the initial, schema-free `.gtkx/env.d.ts` module: just the
 * {@link GTKX_ENV_MODULE_HEADER} with a trailing newline. Used to seed a freshly
 * scaffolded project so its `gtkx-env.d.ts` reference resolves before the first
 * codegen run.
 */
export const renderEmptyGtkxEnvModule = (): string => `${GTKX_ENV_MODULE_HEADER}\n`;
