import { camelCase, sanitizeIdentifier, sourceStringLiteral, upperFirst } from "@gtkx/utils";
import type { ParsedSchema, ParsedSchemaFile } from "./parser.js";

type NamedSchema = {
    schema: ParsedSchema;
    exportName: string;
};

type EnvAssetDeclarations = {
    blocked: string[];
    icons: string[];
    resources: string[];
};

type EnvModuleOptions = {
    references?: string[];
};

const GTKX_ENV_MODULE_HEADER = `/**
 * Project import declarations generated by GTKX. Regenerated by
 * \`gtkx codegen\`, \`gtkx dev\`, and \`gtkx build\`; do not edit.
 */`;

const ID_SEPARATOR = /[._]/;
const NAME_SEPARATOR = "_";

const getExportName = (schemaId: string): string =>
    sanitizeIdentifier(schemaId.split(ID_SEPARATOR).map((part) => camelCase(part)).join(NAME_SEPARATOR));

const collisionError = (file: ParsedSchemaFile, taken: string, schemaId: string, name: string): Error =>
    new Error(
        `${file.fileName} declares ${taken} and ${schemaId}, which both export \`${name}\`. ` +
        "Rename one of the schema ids so that every schema in the file gets an export of its own.",
    );

const getNamedSchemas = (file: ParsedSchemaFile): NamedSchema[] => {
    const owners: Map<string, string> = new Map();

    return file.schemas.map((schema) => {
        const exportName = getExportName(schema.id);
        const taken = owners.get(exportName);

        if (taken !== undefined) {
            throw collisionError(file, taken, schema.id, exportName);
        }

        owners.set(exportName, schema.id);

        return { schema, exportName };
    });
};

const getRuntimeKeys = (schema: ParsedSchema): string => {
    const entries = schema.keys.map(
        (key) => `${sourceStringLiteral(key.name)}: ${sourceStringLiteral(key.kind)}`,
    );

    return `{ ${entries.join(", ")} }`;
};

const renderKeyValues = (values: NonNullable<ParsedSchema["keys"][number]["values"]>, isType: boolean): string => {
    if (Array.isArray(values)) {
        const literal = `[${values.map((value) => sourceStringLiteral(value)).join(", ")}]`;

        return isType ? `readonly ${literal}` : literal;
    }

    const entries = Object.entries(values).map(([nick, number]) => {
        const name = sourceStringLiteral(nick);
        const key = isType ? `readonly ${name}` : `[${name}]`;

        return `${key}: ${String(number)}`;
    });

    return `{ ${entries.join(", ")} }`;
};

const getRuntimeValues = (schema: ParsedSchema): string => {
    const entries = schema.keys.flatMap((key) => key.values === null
        ? []
        : [`${sourceStringLiteral(key.name)}: ${renderKeyValues(key.values, false)}`]);

    return `{ ${entries.join(", ")} }`;
};

const renderRuntimeModule = (file: ParsedSchemaFile): string => {
    const lines: string[] = [];
    const named = getNamedSchemas(file);

    for (const [index, { schema, exportName }] of named.entries()) {
        const keysName = `keys_${String(index)}`;
        const valuesName = `values_${String(index)}`;
        const id = sourceStringLiteral(schema.id);
        lines.push(
            `const ${keysName} = ${getRuntimeKeys(schema)};`,
            `const ${valuesName} = ${getRuntimeValues(schema)};`,
        );

        if (schema.path === null) {
            lines.push(
                `export const ${exportName} = { id: ${id}, keys: ${keysName}, values: ${valuesName}, ` +
                `at: (path) => ({ id: ${id}, path, keys: ${keysName}, values: ${valuesName} }) };`,
            );
        } else {
            lines.push(
                `export const ${exportName} = { id: ${id}, path: null, keys: ${keysName}, values: ${valuesName} };`,
            );
        }
    }

    const first = named[0];

    lines.push(first === undefined ? "export {};" : `export default ${first.exportName};`);

    return lines.join("\n");
};

const sanitizeSummary = (summary: string): string => summary.replaceAll("*/", String.raw`*\/`);

const allocateInterfaceName = (schemaId: string, usedNames: Set<string>): string => {
    const base = `${schemaId
        .split(/[^a-zA-Z0-9]+/)
        .filter((part) => part.length > 0)
        .map((part) => upperFirst(part))
        .join("")}Keys`;

    let name = base;
    let suffix = 2;

    while (usedNames.has(name)) {
        name = `${base}${String(suffix)}`;
        suffix += 1;
    }

    usedNames.add(name);

    return name;
};

const renderKeysType = (name: string, schema: ParsedSchema): string[] => {
    const lines = [`    type ${name} = {`];

    for (const key of schema.keys) {
        if (key.summary !== null) {
            lines.push(`        /** ${sanitizeSummary(key.summary)} */`);
        }

        lines.push(`        ${sourceStringLiteral(key.name)}: ${sourceStringLiteral(key.kind)};`);
    }

    lines.push("    };");

    return lines;
};

const renderValuesType = (name: string, schema: ParsedSchema): string[] => {
    const lines = [`    type ${name}Values = {`];

    for (const key of schema.keys) {
        if (key.values === null) {
            continue;
        }

        lines.push(`        readonly ${sourceStringLiteral(key.name)}: ${renderKeyValues(key.values, true)};`);
    }

    lines.push("    };");

    return lines;
};

const boundRefTypeLines = (interfaceName: string, indent: string): string[] => [
    `${indent}id: string;`,
    `${indent}path: string | null;`,
    `${indent}keys: ${interfaceName};`,
    `${indent}values: ${interfaceName}Values;`,
];

const renderSchemaConst = ({ schema, exportName }: NamedSchema, interfaceName: string): string[] => {
    if (schema.path !== null) {
        return [
            `    const ${exportName}: {`,
            `        id: ${sourceStringLiteral(schema.id)};`,
            ...boundRefTypeLines(interfaceName, " ".repeat(8)).slice(1),
            "    };",
        ];
    }

    return [
        `    const ${exportName}: {`,
        `        id: ${sourceStringLiteral(schema.id)};`,
        `        keys: ${interfaceName};`,
        `        values: ${interfaceName}Values;`,
        "        at(path: string): {",
        ...boundRefTypeLines(interfaceName, " ".repeat(12)),
        "        };",
        "    };",
    ];
};

const renderFileModule = (file: ParsedSchemaFile, usedNames: Set<string>): string[] => {
    const lines = [`declare module ${sourceStringLiteral(file.fileName)} {`];
    const exportNames: string[] = [];

    for (const [index, named] of getNamedSchemas(file).entries()) {
        if (index > 0) {
            lines.push("");
        }

        const interfaceName = allocateInterfaceName(named.schema.id, usedNames);
        lines.push(
            ...renderKeysType(interfaceName, named.schema),
            ...renderValuesType(interfaceName, named.schema),
            "",
            ...renderSchemaConst(named, interfaceName),
        );
        exportNames.push(named.exportName);
    }

    const [firstExport] = exportNames;

    if (firstExport === undefined) {
        lines.push("    export {};");
    } else {
        lines.push("", `    export { ${exportNames.join(", ")} };`, `    export default ${firstExport};`);
    }

    lines.push("}");

    return lines;
};

const renderResourceModule = (specifier: string): string => [
    `declare module ${sourceStringLiteral(specifier)} {`,
    "    const path: string;",
    "    export { path };",
    "    export default path;",
    "}",
].join("\n");

const renderIconModule = (specifier: string): string => [
    `declare module ${sourceStringLiteral(specifier)} {`,
    "    const iconName: string;",
    "    export default iconName;",
    "}",
].join("\n");

const renderBlockedAssetModule = (specifier: string): string => [
    `declare module ${sourceStringLiteral(specifier)} {`,
    "    const assetImportRequiresResourceOrUrlQuery: {",
    "        readonly __gtkxAssetImportRequiresResourceOrUrlQuery: unique symbol;",
    "    };",
    "    export default assetImportRequiresResourceOrUrlQuery;",
    "}",
].join("\n");

const renderEnvModule = (
    files: ParsedSchemaFile[],
    assetDeclarations?: EnvAssetDeclarations,
    options: EnvModuleOptions = {},
): string => {
    const assets = assetDeclarations ?? { blocked: [], icons: [], resources: [] };
    const usedNames: Set<string> = new Set();

    const schemas = files.map((file) => renderFileModule(file, usedNames).join("\n"));

    const blocked = assets.blocked.map((specifier) => renderBlockedAssetModule(specifier));
    const icons = assets.icons.map((specifier) => renderIconModule(specifier));
    const resources = assets.resources.map((specifier) => renderResourceModule(specifier));
    const references = (options.references ?? []).map((path) => `/// <reference path=${JSON.stringify(path)} />`);

    return `${[
        GTKX_ENV_MODULE_HEADER,
        ...references,
        ...blocked,
        ...icons,
        ...resources,
        ...schemas,
    ].join("\n\n")}\n`;
};

export { renderRuntimeModule, renderEnvModule };
