import { upperFirst } from "@gtkx/utils";
import type { ParsedKey, ParsedSchema, ParsedSchemaFile } from "./parser.js";

const GTKX_ENV_MODULE_HEADER = `/**
 * GSettings schema modules generated by GTKX from the project's
 * \`.gschema.xml\` files. Regenerated by \`gtkx codegen\`, \`gtkx dev\`, and
 * \`gtkx build\`; do not edit.
 */`;

const ENUM_KIND = "enum";
const FLAGS_KIND = "flags";

const toJsStringLiteral = (value: string): string =>
    JSON.stringify(value).replaceAll("\u{2028}", String.raw`\u2028`).replaceAll("\u{2029}", String.raw`\u2029`);

const getExportName = (schemaId: string): string => schemaId.replaceAll(".", "_");

const runtimeKindForKey = (key: ParsedKey): string => {
    if (key.enumId !== null) {
        return ENUM_KIND;
    }

    if (key.flagsId !== null) {
        return FLAGS_KIND;
    }

    return key.variantType ?? "";
};

const getRuntimeKeys = (schema: ParsedSchema): string => {
    const entries = schema.keys.map(
        (key) => `${toJsStringLiteral(key.name)}: ${toJsStringLiteral(runtimeKindForKey(key))}`,
    );

    return `{ ${entries.join(", ")} }`;
};

const renderRuntimeModule = (file: ParsedSchemaFile): string => {
    const lines: string[] = [];

    for (const [index, schema] of file.schemas.entries()) {
        const keysName = `keys_${String(index)}`;
        const id = toJsStringLiteral(schema.id);
        lines.push(`const ${keysName} = ${getRuntimeKeys(schema)};`);

        if (schema.path === null) {
            lines.push(
                `export const ${getExportName(schema.id)} = { id: ${id}, keys: ${keysName}, ` +
                `at: (path) => ({ id: ${id}, path, keys: ${keysName} }) };`,
            );
        } else {
            lines.push(`export const ${getExportName(schema.id)} = { id: ${id}, path: null, keys: ${keysName} };`);
        }
    }

    const first = file.schemas[0];

    if (first !== undefined) {
        lines.push(`export default ${getExportName(first.id)};`);
    }

    return lines.join("\n");
};

const sanitizeSummary = (summary: string): string => summary.replaceAll("*/", String.raw`*\/`);

const allocateInterfaceName = (schemaId: string, usedNames: Set<string>): string => {
    const base = `${schemaId
        .split(/[^a-zA-Z0-9]+/)
        .filter((part) => part.length > 0)
        .map((part) => upperFirst(part))
        .join("")}Keys`;

    let name = base;
    let suffix = 2;

    while (usedNames.has(name)) {
        name = `${base}${String(suffix)}`;
        suffix += 1;
    }

    usedNames.add(name);

    return name;
};

const renderKeysType = (name: string, schema: ParsedSchema): string[] => {
    const lines = [`    type ${name} = {`];

    for (const key of schema.keys) {
        if (key.summary !== null) {
            lines.push(`        /** ${sanitizeSummary(key.summary)} */`);
        }

        lines.push(`        ${toJsStringLiteral(key.name)}: ${toJsStringLiteral(runtimeKindForKey(key))};`);
    }

    lines.push("    };");

    return lines;
};

const boundRefTypeLines = (interfaceName: string, indent: string): string[] => [
    `${indent}id: string;`,
    `${indent}path: string | null;`,
    `${indent}keys: ${interfaceName};`,
];

const renderSchemaConst = (schema: ParsedSchema, interfaceName: string): string[] => {
    const exportName = getExportName(schema.id);

    if (schema.path !== null) {
        return [
            `    const ${exportName}: {`,
            `        id: ${toJsStringLiteral(schema.id)};`,
            ...boundRefTypeLines(interfaceName, " ".repeat(8)).slice(1),
            "    };",
        ];
    }

    return [
        `    const ${exportName}: {`,
        `        id: ${JSON.stringify(schema.id)};`,
        `        keys: ${interfaceName};`,
        "        at(path: string): {",
        ...boundRefTypeLines(interfaceName, " ".repeat(12)),
        "        };",
        "    };",
    ];
};

const renderFileModule = (file: ParsedSchemaFile, usedNames: Set<string>): string[] => {
    const lines = [`declare module "${file.fileName}" {`];
    const exportNames: string[] = [];

    for (const [index, schema] of file.schemas.entries()) {
        if (index > 0) {
            lines.push("");
        }

        const interfaceName = allocateInterfaceName(schema.id, usedNames);
        lines.push(...renderKeysType(interfaceName, schema), "", ...renderSchemaConst(schema, interfaceName));
        exportNames.push(getExportName(schema.id));
    }

    const [firstExport] = exportNames;

    if (firstExport !== undefined) {
        lines.push("", `    export { ${exportNames.join(", ")} };`, `    export default ${firstExport};`);
    }

    lines.push("}");

    return lines;
};

const renderEnvModule = (files: ParsedSchemaFile[]): string => {
    const usedNames: Set<string> = new Set();

    const blocks = files
        .filter((file) => file.schemas.length > 0)
        .map((file) => renderFileModule(file, usedNames).join("\n"));

    return `${[GTKX_ENV_MODULE_HEADER, ...blocks].join("\n\n")}\n`;
};

export { renderRuntimeModule, renderEnvModule };
