import { camelCase, sanitizeIdentifier, upperFirst } from "@gtkx/utils";
import type { ParsedKey, ParsedSchema, ParsedSchemaFile } from "./parser.js";

type NamedSchema = {
    schema: ParsedSchema;
    exportName: string;
};

type EnvAssetDeclarations = {
    blocked: string[];
    icons: string[];
    legacy: string[];
    resources: string[];
};

type EnvModuleOptions = {
    references?: string[];
};

const GTKX_ENV_MODULE_HEADER = `/**
 * Project import declarations generated by GTKX. Regenerated by
 * \`gtkx codegen\`, \`gtkx dev\`, and \`gtkx build\`; do not edit.
 */`;

const ENUM_KIND = "enum";
const FLAGS_KIND = "flags";
const ID_SEPARATOR = /[._]/;
const NAME_SEPARATOR = "_";

const toJsStringLiteral = (value: string): string =>
    JSON.stringify(value).replaceAll("\u{2028}", String.raw`\u2028`).replaceAll("\u{2029}", String.raw`\u2029`);

const getExportName = (schemaId: string): string =>
    sanitizeIdentifier(schemaId.split(ID_SEPARATOR).map((part) => camelCase(part)).join(NAME_SEPARATOR));

const collisionError = (file: ParsedSchemaFile, taken: string, schemaId: string, name: string): Error =>
    new Error(
        `${file.fileName} declares ${taken} and ${schemaId}, which both export \`${name}\`. ` +
        "Rename one of the schema ids so that every schema in the file gets an export of its own.",
    );

const getNamedSchemas = (file: ParsedSchemaFile): NamedSchema[] => {
    const owners: Map<string, string> = new Map();

    return file.schemas.map((schema) => {
        const exportName = getExportName(schema.id);
        const taken = owners.get(exportName);

        if (taken !== undefined) {
            throw collisionError(file, taken, schema.id, exportName);
        }

        owners.set(exportName, schema.id);

        return { schema, exportName };
    });
};

const runtimeKindForKey = (key: ParsedKey): string => {
    if (key.enumId !== null) {
        return ENUM_KIND;
    }

    if (key.flagsId !== null) {
        return FLAGS_KIND;
    }

    return key.variantType ?? "";
};

const getRuntimeKeys = (schema: ParsedSchema): string => {
    const entries = schema.keys.map(
        (key) => `${toJsStringLiteral(key.name)}: ${toJsStringLiteral(runtimeKindForKey(key))}`,
    );

    return `{ ${entries.join(", ")} }`;
};

const renderRuntimeModule = (file: ParsedSchemaFile): string => {
    const lines: string[] = [];
    const named = getNamedSchemas(file);

    for (const [index, { schema, exportName }] of named.entries()) {
        const keysName = `keys_${String(index)}`;
        const id = toJsStringLiteral(schema.id);
        lines.push(`const ${keysName} = ${getRuntimeKeys(schema)};`);

        if (schema.path === null) {
            lines.push(
                `export const ${exportName} = { id: ${id}, keys: ${keysName}, ` +
                `at: (path) => ({ id: ${id}, path, keys: ${keysName} }) };`,
            );
        } else {
            lines.push(`export const ${exportName} = { id: ${id}, path: null, keys: ${keysName} };`);
        }
    }

    const first = named[0];

    if (first !== undefined) {
        lines.push(`export default ${first.exportName};`);
    }

    return lines.join("\n");
};

const sanitizeSummary = (summary: string): string => summary.replaceAll("*/", String.raw`*\/`);

const allocateInterfaceName = (schemaId: string, usedNames: Set<string>): string => {
    const base = `${schemaId
        .split(/[^a-zA-Z0-9]+/)
        .filter((part) => part.length > 0)
        .map((part) => upperFirst(part))
        .join("")}Keys`;

    let name = base;
    let suffix = 2;

    while (usedNames.has(name)) {
        name = `${base}${String(suffix)}`;
        suffix += 1;
    }

    usedNames.add(name);

    return name;
};

const renderKeysType = (name: string, schema: ParsedSchema): string[] => {
    const lines = [`    type ${name} = {`];

    for (const key of schema.keys) {
        if (key.summary !== null) {
            lines.push(`        /** ${sanitizeSummary(key.summary)} */`);
        }

        lines.push(`        ${toJsStringLiteral(key.name)}: ${toJsStringLiteral(runtimeKindForKey(key))};`);
    }

    lines.push("    };");

    return lines;
};

const boundRefTypeLines = (interfaceName: string, indent: string): string[] => [
    `${indent}id: string;`,
    `${indent}path: string | null;`,
    `${indent}keys: ${interfaceName};`,
];

const renderSchemaConst = ({ schema, exportName }: NamedSchema, interfaceName: string): string[] => {
    if (schema.path !== null) {
        return [
            `    const ${exportName}: {`,
            `        id: ${toJsStringLiteral(schema.id)};`,
            ...boundRefTypeLines(interfaceName, " ".repeat(8)).slice(1),
            "    };",
        ];
    }

    return [
        `    const ${exportName}: {`,
        `        id: ${JSON.stringify(schema.id)};`,
        `        keys: ${interfaceName};`,
        "        at(path: string): {",
        ...boundRefTypeLines(interfaceName, " ".repeat(12)),
        "        };",
        "    };",
    ];
};

const renderFileModule = (file: ParsedSchemaFile, usedNames: Set<string>): string[] => {
    const lines = [`declare module ${toJsStringLiteral(file.fileName)} {`];
    const exportNames: string[] = [];

    for (const [index, named] of getNamedSchemas(file).entries()) {
        if (index > 0) {
            lines.push("");
        }

        const interfaceName = allocateInterfaceName(named.schema.id, usedNames);
        lines.push(...renderKeysType(interfaceName, named.schema), "", ...renderSchemaConst(named, interfaceName));
        exportNames.push(named.exportName);
    }

    const [firstExport] = exportNames;

    if (firstExport !== undefined) {
        lines.push("", `    export { ${exportNames.join(", ")} };`, `    export default ${firstExport};`);
    }

    lines.push("}");

    return lines;
};

const renderResourceModule = (specifier: string): string => [
    `declare module ${toJsStringLiteral(specifier)} {`,
    "    const path: string;",
    "    export { path };",
    "    export default path;",
    "}",
].join("\n");

const renderIconModule = (specifier: string): string => [
    `declare module ${toJsStringLiteral(specifier)} {`,
    "    const iconName: string;",
    "    export default iconName;",
    "}",
].join("\n");

const renderLegacyAssetModule = (specifier: string): string => [
    `declare module ${toJsStringLiteral(specifier)} {`,
    "    const resourceUri: string;",
    "    const path: string;",
    "    export { path };",
    "    export default resourceUri;",
    "}",
].join("\n");

const renderBlockedAssetModule = (specifier: string): string => [
    `declare module ${toJsStringLiteral(specifier)} {`,
    "    const assetImportRequiresResourceOrUrlQuery: {",
    "        readonly __gtkxAssetImportRequiresResourceOrUrlQuery: unique symbol;",
    "    };",
    "    export default assetImportRequiresResourceOrUrlQuery;",
    "}",
].join("\n");

const renderEnvModule = (
    files: ParsedSchemaFile[],
    assetDeclarations?: EnvAssetDeclarations,
    options: EnvModuleOptions = {},
): string => {
    const assets = assetDeclarations ?? { blocked: [], icons: [], legacy: [], resources: [] };
    const usedNames: Set<string> = new Set();

    const schemas = files
        .filter((file) => file.schemas.length > 0)
        .map((file) => renderFileModule(file, usedNames).join("\n"));

    const blocked = assets.blocked.map((specifier) => renderBlockedAssetModule(specifier));
    const icons = assets.icons.map((specifier) => renderIconModule(specifier));
    const legacy = assets.legacy.map((specifier) => renderLegacyAssetModule(specifier));
    const resources = assets.resources.map((specifier) => renderResourceModule(specifier));
    const references = (options.references ?? []).map((path) => `/// <reference path=${JSON.stringify(path)} />`);

    return `${[
        GTKX_ENV_MODULE_HEADER,
        ...references,
        ...blocked,
        ...icons,
        ...legacy,
        ...resources,
        ...schemas,
    ].join("\n\n")}\n`;
};

export { renderRuntimeModule, renderEnvModule };
