/**
 * React Constants
 *
 * Constants specific to React/JSX codegen.
 */

export { getHiddenProps } from "./hidden-props.js";
export {
    COLUMN_VIEW_WIDGET_NAMES,
    DRAWING_AREA_WIDGET_NAMES,
    DROP_DOWN_WIDGET_NAMES,
    LIST_WIDGET_NAMES,
    NAVIGATION_VIEW_WIDGET_NAMES,
    NOTEBOOK_WIDGET_NAMES,
    PACK_INTERFACE_METHODS,
    PREFIX_SUFFIX_INTERFACE_METHODS,
    SCROLLED_WINDOW_WIDGET_NAMES,
    STACK_WIDGET_NAMES,
    VIRTUAL_CHILDREN_WIDGET_NAMES,
    WIDGET_CLASSIFICATIONS,
    WINDOW_WIDGET_NAMES,
} from "./widget-classification.js";
