/**
 * Helpers for shaping the FFI `.d.ts` output produced by the codegen.
 *
 * The runtime contract documented in `packages/ffi/src/generated/<ns>/<ns>.d.ts`
 * is small:
 *
 * - Per class/boxed/interface: an `interface Foo { … }` carrying the
 *   `__gtype__: number` sentinel (for GType-registered types) and any
 *   readable/writable field declarations, paired with a `class Foo {
 *   static name: string }` declaration so consumers can use the name both
 *   as a type and as a class.
 * - Per enum/flags: a `const` member object plus a `type` alias of the
 *   member union (or `number` for bitfields).
 * - Per free function and constant: a declaration carrying the explicit
 *   return type / value type.
 *
 * The first pass of the rewrite relies on `ts.transpileDeclaration` to
 * produce the `.d.ts` from the same isolated-declaration-friendly `.ts`
 * the writers emit. This module exists as the integration point for any
 * future hand-shaped `.d.ts` post-processing (header banner, JSX namespace
 * augmentation, etc.).
 */

/**
 * Returns the canonical header banner prepended to every generated
 * `.d.ts` file.
 */
export const dtsBanner = (namespaceIdentifier: string): string =>
    `// Generated by @gtkx/codegen for ${namespaceIdentifier}. Do not edit by hand.\n`;
