export { createRef, getNativeId, type NativeHandle, readPointer, writePointer } from "@gtkx/native";
export * from "./batch.js";
export * from "./native/base.js";
export * from "./native/error.js";
export * from "./native/events.js";
export * from "./native/lifecycle.js";
export * from "./native/object.js";
export * from "./registry.js";
import "./cairo/cairo.js";
import "./gobject/value.js";
