export {
    DEFAULT_APPLICATION_ID,
    defineConfig,
    GIR_LIBRARY_PATTERN,
    type GtkxConfig,
    isValidApplicationId,
    LIBRARIES_WILDCARD,
    mergeConfig,
    type ResolvedGtkxConfig,
    type ResolvedReactCompilerOptions,
    resolveReactCompilerOptions,
} from "./config.js";
export {
    createGtkxConfigLoader,
    type GtkxConfigLoader,
    loadGtkxConfig,
    loadResolvedGtkxConfig,
} from "./loader.js";
export {
    ARG_REFS,
    type Arg,
    type ArgRef,
    type AttachRule,
    BUFFER_TEXT_KIND,
    type Call,
    COMPANION_KIND,
    CONTAINER_SLOT_KIND,
    type CompanionRule,
    type ControlledTextRule,
    type GtkxRules,
    isRelationshipKind,
    type JsonValue,
    type KeyedListRule,
    LABEL_TEXT_KIND,
    type LayoutChildRule,
    type ListRule,
    RELATIONSHIP_KINDS,
    RELATIONSHIP_NODE_ELEMENT,
    type ReassertRule,
    type RejectRule,
    type RelationshipKind,
    type RelationshipRule,
    type ResolvedGtkxRules,
    resolveGtkxRules,
    type SelectionRule,
    type SkipRule,
    type SyntheticPropRule,
    TEXT_ANCHOR_KIND,
    TEXT_PAINTABLE_KIND,
    type ValueRule,
    validateGtkxRules,
    WIDGET_PROP_KIND,
    type WriteOnceListRule,
} from "./rule-schema.js";
