import { css } from "@gtkx/css";
import * as Gtk from "@gtkx/ffi/gtk";
import { GtkBox, GtkButton, GtkFlowBox, GtkScrolledWindow } from "@gtkx/react";
import type { Demo } from "../types.js";
import sourceCode from "./flowbox.tsx?raw";

const COLORS = [
    "snow",
    "snow1",
    "snow2",
    "snow3",
    "snow4",
    "ghost white",
    "GhostWhite",
    "white smoke",
    "WhiteSmoke",
    "gainsboro",
    "floral white",
    "FloralWhite",
    "old lace",
    "OldLace",
    "linen",
    "antique white",
    "AntiqueWhite",
    "AntiqueWhite1",
    "AntiqueWhite2",
    "AntiqueWhite3",
    "AntiqueWhite4",
    "papaya whip",
    "PapayaWhip",
    "blanched almond",
    "BlanchedAlmond",
    "bisque",
    "bisque1",
    "bisque2",
    "bisque3",
    "bisque4",
    "peach puff",
    "PeachPuff",
    "PeachPuff1",
    "PeachPuff2",
    "PeachPuff3",
    "PeachPuff4",
    "navajo white",
    "NavajoWhite",
    "NavajoWhite1",
    "NavajoWhite2",
    "NavajoWhite3",
    "NavajoWhite4",
    "moccasin",
    "cornsilk",
    "cornsilk1",
    "cornsilk2",
    "cornsilk3",
    "cornsilk4",
    "ivory",
    "ivory1",
    "ivory2",
    "ivory3",
    "ivory4",
    "lemon chiffon",
    "LemonChiffon",
    "LemonChiffon1",
    "LemonChiffon2",
    "LemonChiffon3",
    "LemonChiffon4",
    "seashell",
    "seashell1",
    "seashell2",
    "seashell3",
    "seashell4",
    "honeydew",
    "honeydew1",
    "honeydew2",
    "honeydew3",
    "honeydew4",
    "mint cream",
    "MintCream",
    "azure",
    "azure1",
    "azure2",
    "azure3",
    "azure4",
    "alice blue",
    "AliceBlue",
    "lavender",
    "lavender blush",
    "LavenderBlush",
    "LavenderBlush1",
    "LavenderBlush2",
    "LavenderBlush3",
    "LavenderBlush4",
    "misty rose",
    "MistyRose",
    "MistyRose1",
    "MistyRose2",
    "MistyRose3",
    "MistyRose4",
    "white",
    "black",
    "dark slate gray",
    "DarkSlateGray",
    "DarkSlateGrey",
    "DarkSlateGray1",
    "DarkSlateGray2",
    "DarkSlateGray3",
    "DarkSlateGray4",
    "dim gray",
    "DimGray",
    "DimGrey",
    "slate gray",
    "SlateGray",
    "SlateGrey",
    "SlateGray1",
    "SlateGray2",
    "SlateGray3",
    "SlateGray4",
    "light slate gray",
    "LightSlateGray",
    "LightSlateGrey",
    "gray",
    "grey",
    "light grey",
    "LightGrey",
    "light gray",
    "LightGray",
    "midnight blue",
    "MidnightBlue",
    "navy",
    "navy blue",
    "NavyBlue",
    "cornflower blue",
    "CornflowerBlue",
    "dark slate blue",
    "DarkSlateBlue",
    "slate blue",
    "SlateBlue",
    "SlateBlue1",
    "SlateBlue2",
    "SlateBlue3",
    "SlateBlue4",
    "medium slate blue",
    "MediumSlateBlue",
    "light slate blue",
    "LightSlateBlue",
    "medium blue",
    "MediumBlue",
    "royal blue",
    "RoyalBlue",
    "RoyalBlue1",
    "RoyalBlue2",
    "RoyalBlue3",
    "RoyalBlue4",
    "blue",
    "blue1",
    "blue2",
    "blue3",
    "blue4",
    "dodger blue",
    "DodgerBlue",
    "DodgerBlue1",
    "DodgerBlue2",
    "DodgerBlue3",
    "DodgerBlue4",
    "deep sky blue",
    "DeepSkyBlue",
    "DeepSkyBlue1",
    "DeepSkyBlue2",
    "DeepSkyBlue3",
    "DeepSkyBlue4",
    "sky blue",
    "SkyBlue",
    "SkyBlue1",
    "SkyBlue2",
    "SkyBlue3",
    "SkyBlue4",
    "light sky blue",
    "LightSkyBlue",
    "LightSkyBlue1",
    "LightSkyBlue2",
    "LightSkyBlue3",
    "LightSkyBlue4",
    "steel blue",
    "SteelBlue",
    "SteelBlue1",
    "SteelBlue2",
    "SteelBlue3",
    "SteelBlue4",
    "light steel blue",
    "LightSteelBlue",
    "LightSteelBlue1",
    "LightSteelBlue2",
    "LightSteelBlue3",
    "LightSteelBlue4",
    "light blue",
    "LightBlue",
    "LightBlue1",
    "LightBlue2",
    "LightBlue3",
    "LightBlue4",
    "powder blue",
    "PowderBlue",
    "pale turquoise",
    "PaleTurquoise",
    "PaleTurquoise1",
    "PaleTurquoise2",
    "PaleTurquoise3",
    "PaleTurquoise4",
    "dark turquoise",
    "DarkTurquoise",
    "medium turquoise",
    "MediumTurquoise",
    "turquoise",
    "turquoise1",
    "turquoise2",
    "turquoise3",
    "turquoise4",
    "cyan",
    "cyan1",
    "cyan2",
    "cyan3",
    "cyan4",
    "light cyan",
    "LightCyan",
    "LightCyan1",
    "LightCyan2",
    "LightCyan3",
    "LightCyan4",
    "cadet blue",
    "CadetBlue",
    "CadetBlue1",
    "CadetBlue2",
    "CadetBlue3",
    "CadetBlue4",
    "medium aquamarine",
    "MediumAquamarine",
    "aquamarine",
    "aquamarine1",
    "aquamarine2",
    "aquamarine3",
    "aquamarine4",
    "dark green",
    "DarkGreen",
    "dark olive green",
    "DarkOliveGreen",
    "DarkOliveGreen1",
    "DarkOliveGreen2",
    "DarkOliveGreen3",
    "DarkOliveGreen4",
    "dark sea green",
    "DarkSeaGreen",
    "DarkSeaGreen1",
    "DarkSeaGreen2",
    "DarkSeaGreen3",
    "DarkSeaGreen4",
    "sea green",
    "SeaGreen",
    "SeaGreen1",
    "SeaGreen2",
    "SeaGreen3",
    "SeaGreen4",
    "medium sea green",
    "MediumSeaGreen",
    "light sea green",
    "LightSeaGreen",
    "pale green",
    "PaleGreen",
    "PaleGreen1",
    "PaleGreen2",
    "PaleGreen3",
    "PaleGreen4",
    "spring green",
    "SpringGreen",
    "SpringGreen1",
    "SpringGreen2",
    "SpringGreen3",
    "SpringGreen4",
    "lawn green",
    "LawnGreen",
    "green",
    "green1",
    "green2",
    "green3",
    "green4",
    "chartreuse",
    "chartreuse1",
    "chartreuse2",
    "chartreuse3",
    "chartreuse4",
    "medium spring green",
    "MediumSpringGreen",
    "green yellow",
    "GreenYellow",
    "lime green",
    "LimeGreen",
    "yellow green",
    "YellowGreen",
    "forest green",
    "ForestGreen",
    "olive drab",
    "OliveDrab",
    "OliveDrab1",
    "OliveDrab2",
    "OliveDrab3",
    "OliveDrab4",
    "dark khaki",
    "DarkKhaki",
    "khaki",
    "khaki1",
    "khaki2",
    "khaki3",
    "khaki4",
    "pale goldenrod",
    "PaleGoldenrod",
    "light goldenrod yellow",
    "LightGoldenrodYellow",
    "light goldenrod",
    "LightGoldenrod",
    "LightGoldenrod1",
    "LightGoldenrod2",
    "LightGoldenrod3",
    "LightGoldenrod4",
    "light yellow",
    "LightYellow",
    "LightYellow1",
    "LightYellow2",
    "LightYellow3",
    "LightYellow4",
    "yellow",
    "yellow1",
    "yellow2",
    "yellow3",
    "yellow4",
    "gold",
    "gold1",
    "gold2",
    "gold3",
    "gold4",
    "goldenrod",
    "goldenrod1",
    "goldenrod2",
    "goldenrod3",
    "goldenrod4",
    "dark goldenrod",
    "DarkGoldenrod",
    "DarkGoldenrod1",
    "DarkGoldenrod2",
    "DarkGoldenrod3",
    "DarkGoldenrod4",
    "rosy brown",
    "RosyBrown",
    "RosyBrown1",
    "RosyBrown2",
    "RosyBrown3",
    "RosyBrown4",
    "indian red",
    "IndianRed",
    "IndianRed1",
    "IndianRed2",
    "IndianRed3",
    "IndianRed4",
    "saddle brown",
    "SaddleBrown",
    "sienna",
    "sienna1",
    "sienna2",
    "sienna3",
    "sienna4",
    "peru",
    "burlywood",
    "burlywood1",
    "burlywood2",
    "burlywood3",
    "burlywood4",
    "beige",
    "wheat",
    "wheat1",
    "wheat2",
    "wheat3",
    "wheat4",
    "sandy brown",
    "SandyBrown",
    "tan",
    "tan1",
    "tan2",
    "tan3",
    "tan4",
    "chocolate",
    "chocolate1",
    "chocolate2",
    "chocolate3",
    "chocolate4",
    "firebrick",
    "firebrick1",
    "firebrick2",
    "firebrick3",
    "firebrick4",
    "brown",
    "brown1",
    "brown2",
    "brown3",
    "brown4",
    "dark salmon",
    "DarkSalmon",
    "salmon",
    "salmon1",
    "salmon2",
    "salmon3",
    "salmon4",
    "light salmon",
    "LightSalmon",
    "LightSalmon1",
    "LightSalmon2",
    "LightSalmon3",
    "LightSalmon4",
    "orange",
    "orange1",
    "orange2",
    "orange3",
    "orange4",
    "dark orange",
    "DarkOrange",
    "DarkOrange1",
    "DarkOrange2",
    "DarkOrange3",
    "DarkOrange4",
    "coral",
    "coral1",
    "coral2",
    "coral3",
    "coral4",
    "light coral",
    "LightCoral",
    "tomato",
    "tomato1",
    "tomato2",
    "tomato3",
    "tomato4",
    "orange red",
    "OrangeRed",
    "OrangeRed1",
    "OrangeRed2",
    "OrangeRed3",
    "OrangeRed4",
    "red",
    "red1",
    "red2",
    "red3",
    "red4",
    "hot pink",
    "HotPink",
    "HotPink1",
    "HotPink2",
    "HotPink3",
    "HotPink4",
    "deep pink",
    "DeepPink",
    "DeepPink1",
    "DeepPink2",
    "DeepPink3",
    "DeepPink4",
    "pink",
    "pink1",
    "pink2",
    "pink3",
    "pink4",
    "light pink",
    "LightPink",
    "LightPink1",
    "LightPink2",
    "LightPink3",
    "LightPink4",
    "pale violet red",
    "PaleVioletRed",
    "PaleVioletRed1",
    "PaleVioletRed2",
    "PaleVioletRed3",
    "PaleVioletRed4",
    "maroon",
    "maroon1",
    "maroon2",
    "maroon3",
    "maroon4",
    "medium violet red",
    "MediumVioletRed",
    "violet red",
    "VioletRed",
    "VioletRed1",
    "VioletRed2",
    "VioletRed3",
    "VioletRed4",
    "magenta",
    "magenta1",
    "magenta2",
    "magenta3",
    "magenta4",
    "violet",
    "plum",
    "plum1",
    "plum2",
    "plum3",
    "plum4",
    "orchid",
    "orchid1",
    "orchid2",
    "orchid3",
    "orchid4",
    "medium orchid",
    "MediumOrchid",
    "MediumOrchid1",
    "MediumOrchid2",
    "MediumOrchid3",
    "MediumOrchid4",
    "dark orchid",
    "DarkOrchid",
    "DarkOrchid1",
    "DarkOrchid2",
    "DarkOrchid3",
    "DarkOrchid4",
    "dark violet",
    "DarkViolet",
    "blue violet",
    "BlueViolet",
    "purple",
    "purple1",
    "purple2",
    "purple3",
    "purple4",
    "medium purple",
    "MediumPurple",
    "MediumPurple1",
    "MediumPurple2",
    "MediumPurple3",
    "MediumPurple4",
    "thistle",
    "thistle1",
    "thistle2",
    "thistle3",
    "thistle4",
    "gray0",
    "grey0",
    "gray1",
    "grey1",
    "gray2",
    "grey2",
    "gray3",
    "grey3",
    "gray4",
    "grey4",
    "gray5",
    "grey5",
    "gray6",
    "grey6",
    "gray7",
    "grey7",
    "gray8",
    "grey8",
    "gray9",
    "grey9",
    "gray10",
    "grey10",
    "gray11",
    "grey11",
    "gray12",
    "grey12",
    "gray13",
    "grey13",
    "gray14",
    "grey14",
    "gray15",
    "grey15",
    "gray16",
    "grey16",
    "gray17",
    "grey17",
    "gray18",
    "grey18",
    "gray19",
    "grey19",
    "gray20",
    "grey20",
    "gray21",
    "grey21",
    "gray22",
    "grey22",
    "gray23",
    "grey23",
    "gray24",
    "grey24",
    "gray25",
    "grey25",
    "gray26",
    "grey26",
    "gray27",
    "grey27",
    "gray28",
    "grey28",
    "gray29",
    "grey29",
    "gray30",
    "grey30",
    "gray31",
    "grey31",
    "gray32",
    "grey32",
    "gray33",
    "grey33",
    "gray34",
    "grey34",
    "gray35",
    "grey35",
    "gray36",
    "grey36",
    "gray37",
    "grey37",
    "gray38",
    "grey38",
    "gray39",
    "grey39",
    "gray40",
    "grey40",
    "gray41",
    "grey41",
    "gray42",
    "grey42",
    "gray43",
    "grey43",
    "gray44",
    "grey44",
    "gray45",
    "grey45",
    "gray46",
    "grey46",
    "gray47",
    "grey47",
    "gray48",
    "grey48",
    "gray49",
    "grey49",
    "gray50",
    "grey50",
    "gray51",
    "grey51",
    "gray52",
    "grey52",
    "gray53",
    "grey53",
    "gray54",
    "grey54",
    "gray55",
    "grey55",
    "gray56",
    "grey56",
    "gray57",
    "grey57",
    "gray58",
    "grey58",
    "gray59",
    "grey59",
    "gray60",
    "grey60",
    "gray61",
    "grey61",
    "gray62",
    "grey62",
    "gray63",
    "grey63",
    "gray64",
    "grey64",
    "gray65",
    "grey65",
    "gray66",
    "grey66",
    "gray67",
    "grey67",
    "gray68",
    "grey68",
    "gray69",
    "grey69",
    "gray70",
    "grey70",
    "gray71",
    "grey71",
    "gray72",
    "grey72",
    "gray73",
    "grey73",
    "gray74",
    "grey74",
    "gray75",
    "grey75",
    "gray76",
    "grey76",
    "gray77",
    "grey77",
    "gray78",
    "grey78",
    "gray79",
    "grey79",
    "gray80",
    "grey80",
    "gray81",
    "grey81",
    "gray82",
    "grey82",
    "gray83",
    "grey83",
    "gray84",
    "grey84",
    "gray85",
    "grey85",
    "gray86",
    "grey86",
    "gray87",
    "grey87",
    "gray88",
    "grey88",
    "gray89",
    "grey89",
    "gray90",
    "grey90",
    "gray91",
    "grey91",
    "gray92",
    "grey92",
    "gray93",
    "grey93",
    "gray94",
    "grey94",
    "gray95",
    "grey95",
    "gray96",
    "grey96",
    "gray97",
    "grey97",
    "gray98",
    "grey98",
    "gray99",
    "grey99",
    "gray100",
    "grey100",
    "dark grey",
    "DarkGrey",
    "dark gray",
    "DarkGray",
    "dark blue",
    "DarkBlue",
    "dark cyan",
    "DarkCyan",
    "dark magenta",
    "DarkMagenta",
    "dark red",
    "DarkRed",
    "light green",
    "LightGreen",
];

const colorStyles = COLORS.map(
    (color) => css`
        & {
            background-color: ${color};
        }
    `,
);

/**
 * Flow Box demo matching the official GTK gtk-demo.
 * GtkFlowBox allows flexible and responsive grids which reflow
 * as needed and support sorting and filtering.
 */
const FlowBoxDemo = () => {
    return (
        <GtkScrolledWindow hscrollbarPolicy={Gtk.PolicyType.NEVER}>
            <GtkFlowBox maxChildrenPerLine={30} selectionMode={Gtk.SelectionMode.NONE} valign={Gtk.Align.START}>
                {COLORS.map((color, index) => (
                    <GtkButton key={color}>
                        <GtkBox widthRequest={24} heightRequest={24} cssClasses={[colorStyles[index] ?? ""]} />
                    </GtkButton>
                ))}
            </GtkFlowBox>
        </GtkScrolledWindow>
    );
};

export const flowboxDemo: Demo = {
    id: "flowbox",
    title: "Flow Box",
    description:
        "GtkFlowBox allows flexible and responsive grids which reflow as needed and support sorting and filtering. The children of a GtkFlowBox are regular widgets.",
    keywords: ["flowbox", "GtkFlowBox", "grid", "wrap", "responsive"],
    component: FlowBoxDemo,
    sourceCode,
};
