import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
    GALLERY_CATEGORIES,
    GALLERY_ENTRIES,
    type GalleryCategory,
    type GalleryEntry,
} from "../screenshots/gallery/manifest.ts";

const website = resolve(import.meta.dirname, "..");
const galleryDir = resolve(website, "docs/gallery");

const upstreamName = (url: string): string => (url.includes("libadwaita") ? "Libadwaita docs" : "GTK docs");

const renderEntry = (entry: GalleryEntry): string => {
    const links = [`[${upstreamName(entry.docUrl)}](${entry.docUrl})`];
    if (entry.guide) links.push(`[GTKX guide](${entry.guide})`);
    return `### ${entry.title}

![${entry.title} rendered by GTKX](./images/${entry.slug}-light.webp){.light-only}
![${entry.title} rendered by GTKX](./images/${entry.slug}-dark.webp){.dark-only}

::: details Source
<<< @/screenshots/gallery/fixtures/${entry.slug}.tsx
:::

${links.join(" · ")}
`;
};

const renderCategoryPage = (category: GalleryCategory): string => {
    const { title, intro } = GALLERY_CATEGORIES[category];
    const entries = GALLERY_ENTRIES.filter((entry) => entry.category === category);
    return `---
editLink: false
---

<!-- Generated by scripts/gallery.ts from screenshots/gallery/manifest.ts. Do not edit by hand. -->

# ${title}

${intro} Every screenshot below is captured from a real GTKX render of the source shown with it.

${entries.map(renderEntry).join("\n")}`;
};

const renderOverview = (): string => {
    const sections = (Object.keys(GALLERY_CATEGORIES) as GalleryCategory[]).map((category) => {
        const { title, intro } = GALLERY_CATEGORIES[category];
        const entries = GALLERY_ENTRIES.filter((entry) => entry.category === category);
        const list = entries.map((entry) => `[${entry.title}](./${category}#${entry.slug})`).join(" · ");
        return `## [${title}](./${category})\n\n${intro}\n\n${list}\n`;
    });
    return `---
editLink: false
---

<!-- Generated by scripts/gallery.ts from screenshots/gallery/manifest.ts. Do not edit by hand. -->

# Widget gallery

Every entry pairs a screenshot captured from a real GTKX render with the exact source that produced it, in both light and dark color schemes. The catalog is curated — GTKX generates components for every GTK4 and Libadwaita class, so anything you find in the upstream documentation works the same way.

${sections.join("\n")}`;
};

mkdirSync(galleryDir, { recursive: true });
writeFileSync(resolve(galleryDir, "index.md"), renderOverview());
for (const category of Object.keys(GALLERY_CATEGORIES) as GalleryCategory[]) {
    writeFileSync(resolve(galleryDir, `${category}.md`), renderCategoryPage(category));
}
console.log(`Gallery pages generated for ${GALLERY_ENTRIES.length} entries.`);
