import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { SourceMessage } from "./source-messages.js";

type I18nTypesResult = {
    isWritten: boolean;
    path: string;
};

const I18N_TYPES_FILENAME = "i18n.d.ts";
const INTERPOLATION_PATTERN = /\{\{[^{}]+\}\}/u;

const stringType = (values: string[]): string =>
    [...new Set(values)].map((value) => JSON.stringify(value)).join(" | ");

const contextField = (context: string | null): string =>
    context === null ? "" : ` context: ${JSON.stringify(context)};`;

const hasInterpolation = (values: string[]): boolean => values.some((value) => INTERPOLATION_PATTERN.test(value));

const pointVariant = (message: SourceMessage): string => {
    const isRequired = message.context !== null || hasInterpolation([message.msgid]);
    const isInterpolated = hasInterpolation([message.msgid]);

    return (
        `{${contextField(message.context)} interpolated: ${String(isInterpolated)}; kind: "point"; ` +
        `required: ${String(isRequired)}; value: ${JSON.stringify(message.msgid)} }`
    );
};

const defaultVariant = (message: SourceMessage): string => {
    const values = [message.singular];
    const isInterpolated = hasInterpolation(values);
    const isRequired = message.context !== null || isInterpolated;

    return (
        `{${contextField(message.context)} defaultValue: ${JSON.stringify(message.singular)}; ` +
        `interpolated: ${String(isInterpolated)}; kind: "default"; required: ${String(isRequired)}; ` +
        `value: ${stringType(values)} }`
    );
};

const requirePlural = (message: SourceMessage): string => {
    if (message.plural === null) {
        throw new Error("Plural translation metadata requires a plural source string");
    }

    return message.plural;
};

const pluralVariant = (message: SourceMessage): string => {
    const plural = requirePlural(message);
    const values = [message.singular, plural];
    const isInterpolated = hasInterpolation(values);

    return (
        `{${contextField(message.context)} defaultValue: ${JSON.stringify(plural)}; ` +
        `interpolated: ${String(isInterpolated)}; kind: "plural"; required: true; ` +
        `value: ${stringType(values)} }`
    );
};

const pluralDefaultsVariant = (message: SourceMessage): string => {
    const plural = requirePlural(message);
    const values = [message.singular, plural];
    const isInterpolated = hasInterpolation(values);

    return (
        `{${contextField(message.context)} defaultValueOne: ${JSON.stringify(message.singular)}; ` +
        `defaultValueOther: ${JSON.stringify(plural)}; interpolated: ${String(isInterpolated)}; ` +
        `kind: "pluralDefaults"; required: true; value: ${stringType(values)} }`
    );
};

const variantsFor = (message: SourceMessage): string[] => {
    if (message.kind === "plural") {
        return [pluralVariant(message)];
    }

    if (message.kind === "pluralDefaults") {
        return [pluralDefaultsVariant(message)];
    }

    return message.kind === "default" ? [defaultVariant(message)] : [pointVariant(message)];
};

const renderRegistry = (messages: SourceMessage[]): string[] => {
    const entries: Map<string, Set<string>> = new Map();

    for (const message of messages) {
        const variants = entries.get(message.msgid) ?? new Set<string>();

        for (const variant of variantsFor(message)) {
            variants.add(variant);
        }

        entries.set(message.msgid, variants);
    }

    return [...entries]
        .toSorted(([left], [right]) => left.localeCompare(right))
        .map(([msgid, variants]) => `        ${JSON.stringify(msgid)}: ${[...variants].join(" | ")};`);
};

const generatedHeader = (): string[] => [
    "/**",
    " * Translation declarations generated by GTKX. Regenerated by",
    " * `gtkx codegen`, `gtkx dev`, and `gtkx build`; do not edit.",
    " */",
];

const renderI18nTypes = (messages: SourceMessage[], isEnabled = true): string => {
    if (!isEnabled) {
        return [...generatedHeader(), "export {};", ""].join("\n");
    }

    return [
        ...generatedHeader(),
        'import "@gtkx/i18n";',
        "",
        'declare module "@gtkx/i18n" {',
        "    interface TranslationRegistry {",
        ...renderRegistry(messages),
        "    }",
        "}",
        "",
    ].join("\n");
};

const i18nTypesPath = (root: string): string => join(root, "node_modules", ".gtkx", I18N_TYPES_FILENAME);

const readFileOrNull = (path: string): string | null => {
    try {
        return readFileSync(path, "utf8");
    } catch {
        return null;
    }
};

const emitI18nTypes = (root: string, messages: SourceMessage[], isEnabled = true): I18nTypesResult => {
    const path = i18nTypesPath(root);
    const content = renderI18nTypes(messages, isEnabled);

    if (readFileOrNull(path) === content) {
        return { isWritten: false, path };
    }

    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);

    return { isWritten: true, path };
};

export { I18N_TYPES_FILENAME, emitI18nTypes, i18nTypesPath };
