import type { CSSInterpolation } from "@emotion/serialize";
import { serializeStyles } from "@emotion/serialize";
import { compile, middleware, rulesheet, serialize, stringify } from "stylis";
import { getGtkCache } from "./cache.js";

/**
 * Branded type for CSS class names generated by {@link css}.
 * @internal
 */
type CSSClassName = string & { __brand: "css" };

const flush = (input: string): void => {
    const sheet = getGtkCache().sheet;
    serialize(
        compile(input),
        middleware([
            stringify,
            rulesheet((rule) => {
                sheet.insert(rule);
            }),
        ]),
    );
};

/**
 * Creates a CSS class from style definitions.
 *
 * Uses Emotion's serializer for hashing and stylis for nested-rule
 * expansion, at-rule scoping, and selector compounding. Nested selectors
 * reference the parent class via `&`, matching Emotion / styled-components
 * semantics.
 *
 * @param args - CSS style definitions (objects, template literals, or interpolations)
 * @returns A unique class name to use with `cssClasses` prop
 *
 * @example
 * ```tsx
 * import { css } from "@gtkx/css";
 *
 * const buttonStyle = css({
 *   padding: "8px 16px",
 *   borderRadius: "4px",
 *   "&:hover": {
 *     backgroundColor: "@accent_bg_color",
 *   },
 * });
 *
 * <GtkButton cssClasses={[buttonStyle]} label="Styled Button" />
 * ```
 *
 * @example
 * ```tsx
 * // Template literal syntax
 * const labelStyle = css`
 *   font-size: 14px;
 *   color: @theme_text_color;
 * `;
 * ```
 *
 * @see {@link cx} for combining class names
 * @see {@link injectGlobal} for global styles
 */
export const css = (...args: CSSInterpolation[]): CSSClassName => {
    const cache = getGtkCache();
    const serialized = serializeStyles(args, cache.registered);
    const className = `${cache.key}-${serialized.name}`;

    if (cache.inserted[serialized.name] === undefined) {
        flush(`.${className}{${serialized.styles}}`);
        cache.inserted[serialized.name] = true;
        cache.registered[className] = serialized.styles;
    }

    return className as CSSClassName;
};

/**
 * Combines class names into an array suitable for the `cssClasses` prop.
 *
 * Filters out falsy values, allowing conditional class application.
 *
 * Note: unlike `@emotion/css`'s `cx`, this does not merge cached styles into a
 * single class — GTK widgets accept an array via `cssClasses`, so we keep the
 * names separate. Use it the same way you would use `clsx` or `classnames`.
 *
 * @param classNames - Class names, booleans, undefined, or null values
 * @returns Array of valid class names
 *
 * @example
 * ```tsx
 * import { css, cx } from "@gtkx/css";
 *
 * const base = css({ padding: "8px" });
 * const active = css({ backgroundColor: "@accent_bg_color" });
 *
 * <GtkButton
 *   cssClasses={cx(base, isActive && active, "custom-class")}
 *   label="Button"
 * />
 * ```
 */
export const cx = (...classNames: (string | boolean | undefined | null)[]): string[] =>
    classNames.filter((cn): cn is string => typeof cn === "string" && cn.length > 0);

/**
 * Injects global CSS styles without a wrapping class.
 *
 * Use for application-wide styles, CSS variables, or styling native GTK widgets.
 *
 * @param args - CSS style definitions
 *
 * @example
 * ```tsx
 * import { injectGlobal } from "@gtkx/css";
 *
 * injectGlobal`
 *   window {
 *     background-color: @theme_bg_color;
 *   }
 *
 *   .title-1 {
 *     font-size: 24px;
 *     font-weight: bold;
 *   }
 * `;
 * ```
 *
 * @see {@link css} for scoped class-based styles
 */
export const injectGlobal = (...args: CSSInterpolation[]): void => {
    const cache = getGtkCache();
    const serialized = serializeStyles(args, cache.registered);
    const insertedKey = `global-${serialized.name}`;

    if (cache.inserted[insertedKey] === undefined) {
        flush(serialized.styles);
        cache.inserted[insertedKey] = true;
    }
};
