import * as Gtk from "@gtkx/gi/gtk";

const FROM_AUTHOR = 1;
const FROM_CONTENT = 2;
const PROHIBITED = 4;

const NAMING: Partial<Record<Gtk.AccessibleRole, number>> = {
    [Gtk.AccessibleRole.ALERT]: FROM_AUTHOR,
    [Gtk.AccessibleRole.ALERT_DIALOG]: FROM_AUTHOR,
    [Gtk.AccessibleRole.APPLICATION]: FROM_AUTHOR,
    [Gtk.AccessibleRole.ARTICLE]: FROM_AUTHOR,
    [Gtk.AccessibleRole.BANNER]: FROM_AUTHOR,
    [Gtk.AccessibleRole.BLOCK_QUOTE]: FROM_AUTHOR,
    [Gtk.AccessibleRole.BUTTON]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.CAPTION]: PROHIBITED,
    [Gtk.AccessibleRole.CELL]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.CHECKBOX]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.COLUMN_HEADER]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.COMBO_BOX]: FROM_AUTHOR,
    [Gtk.AccessibleRole.COMMAND]: PROHIBITED,
    [Gtk.AccessibleRole.COMMENT]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.COMPOSITE]: PROHIBITED,
    [Gtk.AccessibleRole.DIALOG]: FROM_AUTHOR,
    [Gtk.AccessibleRole.DOCUMENT]: FROM_AUTHOR,
    [Gtk.AccessibleRole.FEED]: FROM_AUTHOR,
    [Gtk.AccessibleRole.FORM]: FROM_AUTHOR,
    [Gtk.AccessibleRole.GENERIC]: PROHIBITED,
    [Gtk.AccessibleRole.GRID]: FROM_AUTHOR,
    [Gtk.AccessibleRole.GRID_CELL]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.GROUP]: FROM_AUTHOR,
    [Gtk.AccessibleRole.HEADING]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.IMG]: FROM_AUTHOR,
    [Gtk.AccessibleRole.INPUT]: PROHIBITED,
    [Gtk.AccessibleRole.LABEL]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.LANDMARK]: PROHIBITED,
    [Gtk.AccessibleRole.LEGEND]: PROHIBITED,
    [Gtk.AccessibleRole.LINK]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.LIST]: FROM_AUTHOR,
    [Gtk.AccessibleRole.LIST_BOX]: FROM_AUTHOR,
    [Gtk.AccessibleRole.LIST_ITEM]: FROM_AUTHOR,
    [Gtk.AccessibleRole.LOG]: FROM_AUTHOR,
    [Gtk.AccessibleRole.MAIN]: FROM_AUTHOR,
    [Gtk.AccessibleRole.MARQUEE]: FROM_AUTHOR,
    [Gtk.AccessibleRole.MATH]: FROM_AUTHOR,
    [Gtk.AccessibleRole.METER]: FROM_AUTHOR,
    [Gtk.AccessibleRole.MENU]: FROM_AUTHOR,
    [Gtk.AccessibleRole.MENU_BAR]: FROM_AUTHOR,
    [Gtk.AccessibleRole.MENU_ITEM]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.MENU_ITEM_CHECKBOX]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.MENU_ITEM_RADIO]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.NAVIGATION]: FROM_AUTHOR,
    [Gtk.AccessibleRole.NONE]: PROHIBITED,
    [Gtk.AccessibleRole.NOTE]: FROM_AUTHOR,
    [Gtk.AccessibleRole.OPTION]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.PARAGRAPH]: PROHIBITED,
    [Gtk.AccessibleRole.PRESENTATION]: PROHIBITED,
    [Gtk.AccessibleRole.PROGRESS_BAR]: FROM_AUTHOR,
    [Gtk.AccessibleRole.RADIO]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.RADIO_GROUP]: FROM_AUTHOR,
    [Gtk.AccessibleRole.RANGE]: PROHIBITED,
    [Gtk.AccessibleRole.REGION]: FROM_AUTHOR,
    [Gtk.AccessibleRole.ROW]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.ROW_GROUP]: FROM_AUTHOR,
    [Gtk.AccessibleRole.ROW_HEADER]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.SCROLLBAR]: FROM_AUTHOR,
    [Gtk.AccessibleRole.SEARCH]: FROM_AUTHOR,
    [Gtk.AccessibleRole.SEARCH_BOX]: FROM_AUTHOR,
    [Gtk.AccessibleRole.SECTION]: PROHIBITED,
    [Gtk.AccessibleRole.SECTION_HEAD]: PROHIBITED,
    [Gtk.AccessibleRole.SELECT]: PROHIBITED,
    [Gtk.AccessibleRole.SEPARATOR]: FROM_AUTHOR,
    [Gtk.AccessibleRole.SLIDER]: FROM_AUTHOR,
    [Gtk.AccessibleRole.SPIN_BUTTON]: FROM_AUTHOR,
    [Gtk.AccessibleRole.STATUS]: FROM_AUTHOR,
    [Gtk.AccessibleRole.STRUCTURE]: PROHIBITED,
    [Gtk.AccessibleRole.SWITCH]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.TAB]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.TABLE]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TAB_LIST]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TAB_PANEL]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TERMINAL]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TEXT_BOX]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TIME]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TIMER]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TOGGLE_BUTTON]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TOOLBAR]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TOOLTIP]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.TREE]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TREE_GRID]: FROM_AUTHOR,
    [Gtk.AccessibleRole.TREE_ITEM]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.WIDGET]: FROM_AUTHOR | FROM_CONTENT,
    [Gtk.AccessibleRole.WINDOW]: FROM_AUTHOR,
};

const namingFor = (role: Gtk.AccessibleRole): number => NAMING[role] ?? 0;
const isNameProhibited = (role: Gtk.AccessibleRole): boolean => (namingFor(role) & PROHIBITED) !== 0;
const isNameFromAuthor = (role: Gtk.AccessibleRole): boolean => (namingFor(role) & FROM_AUTHOR) !== 0;

export { isNameFromAuthor, isNameProhibited };
