import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import * as p from "@clack/prompts";
import { isValidApplicationId } from "@gtkx/config";
import { errorMessage, upperFirst } from "@gtkx/utils";
import { addDependency, detectPackageManager as nypmDetectPackageManager } from "nypm";
import { x } from "tinyexec";
import { isKnownPackageManager, isValidProjectName, PACKAGE_MANAGERS, type PackageManager } from "./options.js";
import { listTemplates, renderFile, type TemplateContext } from "./templates.js";
import { version as selfVersion } from "./version.js";

const GTKX_ENV_MODULE_HEADER = `/**
 * Generated by \`gtkx codegen\`, \`gtkx dev\`, and \`gtkx build\`; do not edit.
 */`;

export type CreateOptions = {
    name?: string | undefined;
    applicationId?: string | undefined;
    packageManager?: PackageManager | undefined;
    includeTesting?: boolean | undefined;
    interactive?: boolean | undefined;
    overwrite?: boolean | undefined;
};

type ResolvedOptions = {
    name: string;
    applicationId: string;
    packageManager: PackageManager;
    includeTesting: boolean;
};

const DEPENDENCIES = ["@gtkx/css", "@gtkx/ffi", "@gtkx/native", "@gtkx/react", "react"];

const DEV_DEPENDENCIES = ["@gtkx/cli", "@gtkx/config", "@types/react", "typescript", "vite"];

const TESTING_DEV_DEPENDENCIES = ["@gtkx/testing", "vitest"];

const DEV_COMMAND: Record<PackageManager, string> = Object.fromEntries(
    PACKAGE_MANAGERS.map((manager) => [manager.value, manager.devCommand]),
) as Record<PackageManager, string>;

const pinGtkxDependency = (name: string, version: string): string =>
    name.startsWith("@gtkx/") ? `${name}@^${version}` : name;

const getDevCommand = (packageManager: PackageManager): string => DEV_COMMAND[packageManager];

const titleFromName = (name: string): string => name.split("-").map(upperFirst).join(" ");

const suggestApplicationId = (name: string): string => `com.${name.replaceAll("-", "")}.app`;

const getDevDependencies = (includeTesting: boolean): string[] => {
    const devDeps = [...DEV_DEPENDENCIES];
    if (includeTesting) {
        devDeps.push(...TESTING_DEV_DEPENDENCIES);
    }
    return devDeps;
};

const guardCancellation = <T>(value: T | symbol): T => {
    if (p.isCancel(value)) {
        p.cancel("Operation canceled");
        process.exit(0);
    }
    return value as T;
};

const validateProjectName = (value: string | undefined): string | undefined => {
    if (!value) return "Project name is required";
    if (!isValidProjectName(value)) {
        return "Project name must be lowercase letters, numbers, and hyphens only";
    }
    return undefined;
};

const validateApplicationIdInput = (value: string | undefined): string | undefined => {
    if (!value) return "Application ID is required";
    if (!isValidApplicationId(value)) {
        return "Application ID must be reverse domain notation (e.g., com.example.myapp)";
    }
    return undefined;
};

const fail = (message: string): never => {
    p.log.error(message);
    process.exit(1);
};

const promptName = async (): Promise<string> =>
    guardCancellation(
        await p.text({
            message: "Project name",
            placeholder: "my-app",
            validate: (value) => validateProjectName(value),
        }),
    );

const promptApplicationId = async (name: string): Promise<string> => {
    const defaultApplicationId = suggestApplicationId(name);
    return guardCancellation(
        await p.text({
            message: "Application ID",
            placeholder: defaultApplicationId,
            initialValue: defaultApplicationId,
            validate: validateApplicationIdInput,
        }),
    );
};

const detectPackageManager = async (cwd: string): Promise<PackageManager | undefined> => {
    const detected = await nypmDetectPackageManager(cwd, { includeParentDirs: true });
    if (!detected) return undefined;
    return isKnownPackageManager(detected.name) ? detected.name : undefined;
};

const promptPackageManager = async (): Promise<PackageManager> => {
    const detected = await detectPackageManager(process.cwd()).catch(() => undefined);
    const initial: PackageManager = detected ?? "pnpm";
    return guardCancellation(
        await p.select<PackageManager>({
            message: "Package manager",
            options: PACKAGE_MANAGERS.map((manager) => {
                const hint = detected === manager.value ? "detected" : manager.recommended ? "recommended" : undefined;
                return { value: manager.value, label: manager.label, ...(hint === undefined ? {} : { hint }) };
            }),
            initialValue: initial,
        }),
    );
};

const promptTesting = async (): Promise<boolean> =>
    guardCancellation(
        await p.confirm({
            message: "Include testing setup (Vitest)?",
            initialValue: true,
        }),
    );

const emptyDir = (root: string): void => {
    rmSync(root, { recursive: true, force: true });
};

const validateResolvedOptions = (name: string, applicationId: string): void => {
    const nameError = validateProjectName(name);
    if (nameError) fail(nameError);
    const applicationIdError = validateApplicationIdInput(applicationId);
    if (applicationIdError) fail(applicationIdError);
};

const confirmOverwrite = async (name: string, options: CreateOptions): Promise<boolean> => {
    if (!options.interactive) return options.overwrite === true;
    return guardCancellation(
        await p.confirm({
            message: `Directory "${name}" already exists. Overwrite its contents?`,
            initialValue: false,
        }),
    );
};

const handleExistingDirectory = async (root: string, name: string, options: CreateOptions): Promise<void> => {
    if (!existsSync(root)) return;
    if (await confirmOverwrite(name, options)) {
        emptyDir(root);
        return;
    }
    fail(`Directory "${name}" already exists`);
};

const resolveName = async (options: CreateOptions): Promise<string> => {
    if (options.name !== undefined) return options.name;
    if (!options.interactive) return fail("Project name is required");
    return promptName();
};

const resolveOptions = async (options: CreateOptions): Promise<ResolvedOptions> => {
    const name = await resolveName(options);

    const applicationId =
        options.applicationId ?? (options.interactive ? await promptApplicationId(name) : suggestApplicationId(name));

    validateResolvedOptions(name, applicationId);

    const root = resolve(process.cwd(), name);
    await handleExistingDirectory(root, name, options);

    const packageManager =
        options.packageManager ??
        (options.interactive
            ? await promptPackageManager()
            : ((await detectPackageManager(process.cwd()).catch(() => undefined)) ?? "pnpm"));

    const includeTesting = options.includeTesting ?? (options.interactive ? await promptTesting() : true);

    return { name, applicationId, packageManager, includeTesting };
};

const TESTING_TEMPLATES = new Set(["vitest.config.ts", "tests/app.test.tsx"]);
const PACKAGE_JSON_TEMPLATE = "package.json";

const isTemplateIncluded = (templateRelativePath: string, resolved: ResolvedOptions): boolean =>
    TESTING_TEMPLATES.has(templateRelativePath) ? resolved.includeTesting : true;

const addTestScript = (root: string): void => {
    const packageJsonPath = join(root, PACKAGE_JSON_TEMPLATE);
    const manifest = JSON.parse(readFileSync(packageJsonPath, "utf-8")) as {
        scripts: Record<string, string>;
    };
    manifest.scripts.test = "vitest";
    writeFileSync(packageJsonPath, `${JSON.stringify(manifest, null, 4)}\n`);
};

const scaffoldProject = (root: string, resolved: ResolvedOptions): void => {
    const { name, applicationId, includeTesting } = resolved;
    const context: TemplateContext = { name, applicationId, title: titleFromName(name), includeTesting };

    mkdirSync(root, { recursive: true });

    for (const template of listTemplates()) {
        if (!isTemplateIncluded(template, resolved)) continue;

        const destination = join(root, template);
        mkdirSync(dirname(destination), { recursive: true });
        writeFileSync(destination, renderFile(template, context));
    }

    if (includeTesting) {
        addTestScript(root);
    }
};

type InstallDependenciesOptions = {
    cwd: string;
    packageManager: PackageManager;
    dependencies: string[];
    dev: boolean;
};

const installDependencies = async (options: InstallDependenciesOptions): Promise<void> => {
    const { cwd, packageManager, dependencies, dev } = options;
    await addDependency(dependencies, { cwd, packageManager, dev, silent: true });
};

type InstallAllOptions = {
    root: string;
    name: string;
    packageManager: PackageManager;
    devDependencies: string[];
};

const installAllDependencies = async (options: InstallAllOptions): Promise<void> => {
    const { root, name, packageManager, devDependencies } = options;
    const spinner = p.spinner();
    spinner.start("Installing dependencies...");

    const pin = (names: string[]): string[] => names.map((dependency) => pinGtkxDependency(dependency, selfVersion));

    try {
        await installDependencies({ cwd: root, packageManager, dependencies: pin(DEPENDENCIES), dev: false });
        await installDependencies({ cwd: root, packageManager, dependencies: pin(devDependencies), dev: true });
        spinner.stop("Dependencies installed!");
    } catch (error) {
        spinner.stop("Failed to install dependencies");
        p.log.error(`Error: ${errorMessage(error)}`);
        p.log.info("You can install dependencies manually by running:");
        p.log.info(`  cd ${name}`);
    }
};

const writeInitialEnvModule = (root: string): void => {
    const storeDir = join(root, "node_modules", ".gtkx");
    mkdirSync(storeDir, { recursive: true });
    writeFileSync(join(storeDir, "env.d.ts"), `${GTKX_ENV_MODULE_HEADER}\n`);
};

const initializeGitRepo = async (root: string): Promise<void> => {
    const spinner = p.spinner();
    spinner.start("Initializing git repository...");
    try {
        const opts = { nodeOptions: { cwd: root }, throwOnError: true } as const;
        await x("git", ["init"], opts);
        await x("git", ["add", "-A"], opts);
        await x("git", ["commit", "-m", "Initial commit"], opts);
        spinner.stop("Git repository initialized!");
    } catch {
        spinner.stop("Failed to initialize git repository");
    }
};

const HEADLESS_COMPOSITOR_NOTE = `

To run tests, you need a headless Wayland compositor installed:
  Fedora: sudo dnf install weston
  Ubuntu: sudo apt install weston`;

const printNextSteps = (resolved: ResolvedOptions): void => {
    const devCmd = getDevCommand(resolved.packageManager);
    const nextSteps = `cd ${resolved.name}\n${devCmd}`;
    const testingNote = resolved.includeTesting ? HEADLESS_COMPOSITOR_NOTE : "";
    p.note(`${nextSteps}${testingNote}`, "Next steps");
};

export const scaffold = async (options: CreateOptions = {}): Promise<void> => {
    p.intro("Create gtkx App");

    const resolved = await resolveOptions(options);
    const root = resolve(process.cwd(), resolved.name);
    const devDeps = getDevDependencies(resolved.includeTesting);

    const projectSpinner = p.spinner();
    projectSpinner.start("Creating project structure...");
    scaffoldProject(root, resolved);
    projectSpinner.stop("Project structure created!");

    await installAllDependencies({
        root,
        name: resolved.name,
        packageManager: resolved.packageManager,
        devDependencies: devDeps,
    });
    writeInitialEnvModule(root);
    await initializeGitRepo(root);

    printNextSteps(resolved);
};
