import * as p from "@clack/prompts";
import { APPLICATION_ID_MAX_LENGTH, isValidApplicationId } from "@gtkx/config/internal";
import { errorMessage, tryResolveExecutable, upperFirst } from "@gtkx/utils";
import { execFileSync } from "node:child_process";
import { lstatSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { addDependency, detectPackageManager as nypmDetectPackageManager } from "nypm";
import { x } from "tinyexec";
import packageManifest from "../package.json" with { type: "json" };
import { writeBuildAllowance } from "./build-allowance.js";
import { OperationCanceledError, ScaffoldAbortedError } from "./errors.js";
import { getInstallHint } from "./install-hints.js";
import { updateManifest } from "./manifest.js";
import {
    isKnownPackageManager,
    PACKAGE_MANAGER_VALUES,
    PACKAGE_MANAGERS,
    type PackageManager,
} from "./package-managers.js";
import { isValidProjectName } from "./project-name.js";
import { listTemplates, renderFile, type TemplateContext } from "./templates.js";

type CreateOptions = {
    name?: string | undefined;
    applicationId?: string | undefined;
    displayName?: string | undefined;
    packageManager?: string | undefined;
    isTypescript?: boolean | undefined;
    shouldIncludeTesting?: boolean | undefined;
    isInteractive?: boolean | undefined;
    shouldOverwrite?: boolean | undefined;
};

type ResolvedOptions = {
    target: string;
    root: string;
    isCurrentDirectory: boolean;
    name: string;
    displayName: string;
    applicationId: string;
    packageManager: PackageManager;
    isTypescript: boolean;
    shouldIncludeTesting: boolean;
    shouldInitializeGit: boolean;
};

type ScaffoldFile = { destination: string; contents: string };

type InstallDependenciesOptions = {
    cwd: string;
    packageManager: PackageManager;
    dependencies: string[];
    isDev: boolean;
};

type InstallAllOptions = {
    resolved: ResolvedOptions;
    devDependencies: string[];
};

type InstallFailureOptions = {
    error: unknown;
    resolved: ResolvedOptions;
    devDependencies: string[];
};

type SpinnerStep = {
    pending: string;
    done: string;
    failed: string;
    run: () => Promise<void>;
    explain?: ((error: unknown) => void) | undefined;
};

const selfVersion = packageManifest.version;
const ICON_TEMPLATE_NAME = "icon.svg";

const GTKX_ENV_MODULE_HEADER = `/**
 * Generated by \`gtkx codegen\`, \`gtkx dev\`, and \`gtkx build\`; do not edit.
 */`;

const DEPENDENCIES = ["@gtkx/cairo", "@gtkx/css", "@gtkx/runtime", "@gtkx/react", "react"];
const DEV_DEPENDENCIES = ["@gtkx/cli", "@gtkx/config", "@gtkx/mcp", "vite"];
const TYPESCRIPT_DEV_DEPENDENCIES = ["@types/node", "@types/react", "typescript"];
const TESTING_DEV_DEPENDENCIES = ["@gtkx/testing", "vitest"];

const DEV_COMMAND: Record<PackageManager, string> = Object.fromEntries(
    PACKAGE_MANAGERS.map((manager) => [manager.value, manager.devCommand]),
) as Record<PackageManager, string>;

const ADD_COMMAND: Record<PackageManager, string> = Object.fromEntries(
    PACKAGE_MANAGERS.map((manager) => [manager.value, manager.addCommand]),
) as Record<PackageManager, string>;

const INHERITED_SCRIPT_POLICY_VARS = ["npm_config_allow_scripts", "npm_config_allow-scripts"];
const TESTING_TEMPLATES = new Set(["vitest.config.ts", "tests/app.test.tsx"]);
const TYPESCRIPT_TEMPLATES = new Set(["tsconfig.json", "src/gtkx-env.d.ts"]);

const HEADLESS_COMPOSITOR_NOTE = `

To run tests, you need a headless Wayland compositor installed:
  Fedora: sudo dnf install sway
  Ubuntu: sudo apt install sway`;

const RECOVERY_HEADING = "Finish the setup by adding the dependencies again, which is safe to repeat:";
const APPLICATION_ID_FORMAT_ERROR = "Application ID must be reverse domain notation (e.g., com.example.myapp)";
const APPLICATION_ID_PREFIX = "com.";
const APPLICATION_ID_SUFFIX = ".app";

const APPLICATION_ID_SEGMENT_LIMIT = APPLICATION_ID_MAX_LENGTH - APPLICATION_ID_PREFIX.length -
    APPLICATION_ID_SUFFIX.length;

const displayNameFromProjectName = (name: string): string =>
    name.split("-").map((part) => upperFirst(part)).join(" ");

const gitConfigValue = (key: string): string | null => {
    const git = tryResolveExecutable("git");

    if (git === undefined) {
        return null;
    }

    try {
        return execFileSync(git, ["config", "--get", key], { encoding: "utf8" }).trim() || null;
    } catch {
        return null;
    }
};

const applicationIdSegment = (name: string): string => {
    const compact = name.replaceAll("-", "");
    const segment = /^[A-Za-z_]/.test(compact) ? compact : `_${compact}`;

    return segment.slice(0, APPLICATION_ID_SEGMENT_LIMIT);
};

const suggestApplicationId = (name: string): string =>
    `${APPLICATION_ID_PREFIX}${applicationIdSegment(name)}${APPLICATION_ID_SUFFIX}`;

const stripTrailingSlashes = (value: string): string => {
    let end = value.length;

    while (end > 0 && value[end - 1] === "/") {
        end--;
    }

    return value.slice(0, end);
};

const formatTargetDir = (target: string): string =>
    stripTrailingSlashes(target.trim().replaceAll(/[<>:"\\|?*]/g, ""));

const deriveProjectName = (target: string): string => basename(resolve(process.cwd(), target));

const isDirEmpty = (dir: string): boolean => {
    const entries = readdirSync(dir);

    return entries.length === 0 || (entries.length === 1 && entries[0] === ".git");
};

const shouldInitializeGit = (root: string): boolean => {
    const entry = lstatSync(root, { throwIfNoEntry: false });

    return entry === undefined || (entry.isDirectory() && readdirSync(root).length === 0);
};

const getDevDependencies = ({
    isTypescript,
    shouldIncludeTesting,
}: Pick<ResolvedOptions, "isTypescript" | "shouldIncludeTesting">): string[] => {
    const devDeps = [...DEV_DEPENDENCIES];

    if (isTypescript) {
        devDeps.push(...TYPESCRIPT_DEV_DEPENDENCIES);
    }

    if (shouldIncludeTesting) {
        devDeps.push(...TESTING_DEV_DEPENDENCIES);
    }

    return devDeps;
};

const guardCancellation = <T>(value: T | symbol): T => {
    if (p.isCancel(value)) {
        p.cancel("Operation canceled");
        throw new OperationCanceledError();
    }

    return value;
};

const validateProjectName = (value: string | undefined): string | undefined => {
    if (!value) {
        return "Project name is required";
    }

    if (!isValidProjectName(value)) {
        return "Project name must be lowercase letters, numbers, and hyphens only";
    }

    return undefined;
};

const validateApplicationIdFormat = (value: string): string | undefined =>
    isValidApplicationId(value) ? undefined : APPLICATION_ID_FORMAT_ERROR;

const validateApplicationIdInput = (value: string | undefined): string | undefined =>
    value ? validateApplicationIdFormat(value) : "Application ID is required";

const validateApplicationIdAnswer = (value: string | undefined): string | undefined =>
    value ? validateApplicationIdFormat(value) : undefined;

const validateDisplayName = (value: string | undefined): string | undefined => {
    if (value === undefined || value.trim().length === 0) {
        return "Display name is required";
    }

    return value.includes("\n") || value.includes("\r") ? "Display name must be a single line" : undefined;
};

const validateDisplayNameAnswer = (value: string | undefined): string | undefined =>
    value ? validateDisplayName(value) : undefined;

const fail = (message: string): never => {
    p.log.error(message);
    throw new ScaffoldAbortedError(message);
};

const requestedPackageManager = (value: string | undefined): PackageManager | undefined => {
    if (value === undefined) {
        return undefined;
    }

    if (!isKnownPackageManager(value)) {
        return fail(`Unknown package manager "${value}". Expected one of: ${PACKAGE_MANAGER_VALUES.join(", ")}`);
    }

    return value;
};

const validateTargetDir = (target: string): string | undefined => {
    if (!target) {
        return "Project directory is required";
    }

    return validateProjectName(deriveProjectName(target));
};

const validateTargetAnswer = (value: string | undefined): string | undefined =>
    validateTargetDir(formatTargetDir(value ?? ""));

const promptTarget = async (): Promise<string> =>
    formatTargetDir(
        guardCancellation(
            await p.text({
                message: "Project directory",
                placeholder: "my-app",
                validate: validateTargetAnswer,
            }),
        ),
    );

const promptApplicationId = async (name: string): Promise<string> => {
    const defaultApplicationId = suggestApplicationId(name);

    return guardCancellation(
        await p.text({
            message: "Application ID",
            placeholder: defaultApplicationId,
            defaultValue: defaultApplicationId,
            validate: validateApplicationIdAnswer,
        }),
    );
};

const promptDisplayName = async (name: string): Promise<string> => {
    const defaultDisplayName = displayNameFromProjectName(name);

    return guardCancellation(
        await p.text({
            message: "Display name",
            placeholder: defaultDisplayName,
            defaultValue: defaultDisplayName,
            validate: validateDisplayNameAnswer,
        }),
    );
};

const packageManagerOption = (manager: (typeof PACKAGE_MANAGERS)[number], detected: PackageManager | undefined) => {
    let hint: string | undefined;

    if (detected === manager.value) {
        hint = "detected";
    } else if (manager.isRecommended) {
        hint = "recommended";
    }

    return { value: manager.value, label: manager.label, ...(hint !== undefined && { hint }) };
};

const detectedPackageManager = async (): Promise<PackageManager | undefined> => {
    try {
        const detected = await nypmDetectPackageManager(process.cwd(), { includeParentDirs: true });

        return detected && isKnownPackageManager(detected.name) ? detected.name : undefined;
    } catch {
        return undefined;
    }
};

const promptPackageManager = async (): Promise<PackageManager> => {
    const detected = await detectedPackageManager();
    const initial: PackageManager = detected ?? "pnpm";

    return guardCancellation(
        await p.select<PackageManager>({
            message: "Package manager",
            options: PACKAGE_MANAGERS.map((manager) => packageManagerOption(manager, detected)),
            initialValue: initial,
        }),
    );
};

const isOptionEnabled = async (
    value: boolean | undefined,
    isInteractive: boolean | undefined,
    message: string,
): Promise<boolean> =>
    value ??
    (isInteractive
        ? guardCancellation(await p.confirm({ message, initialValue: true }))
        : true);

const shouldOverwriteDirectory = async (target: string, options: CreateOptions): Promise<boolean> => {
    if (!options.isInteractive) {
        return options.shouldOverwrite === true;
    }

    return guardCancellation(
        await p.confirm({
            message: `Directory "${target}" is not empty. Replace scaffold files?`,
            initialValue: false,
        }),
    );
};

const validateTargetAvailability = async (root: string, target: string, options: CreateOptions): Promise<void> => {
    const stats = statSync(root, { throwIfNoEntry: false });

    if (stats === undefined) {
        return;
    }

    if (!stats.isDirectory()) {
        return fail(`Target "${target}" is not a directory`);
    }

    if (isDirEmpty(root)) {
        return;
    }

    if (await shouldOverwriteDirectory(target, options)) {
        return;
    }

    fail(`Directory "${target}" is not empty`);
};

const resolveTarget = async (options: CreateOptions): Promise<string> => {
    if (options.name === undefined && options.isInteractive) {
        return promptTarget();
    }

    const target = formatTargetDir(options.name ?? "");
    const error = validateTargetDir(target);

    return error === undefined ? target : fail(error);
};

const resolveApplicationId = async (options: CreateOptions, name: string): Promise<string> => {
    const applicationId = options.applicationId ??
        (options.isInteractive ? await promptApplicationId(name) : suggestApplicationId(name));

    const error = validateApplicationIdInput(applicationId);

    return error === undefined ? applicationId : fail(error);
};

const resolveDisplayName = async (options: CreateOptions, name: string): Promise<string> => {
    const value = options.displayName ??
        (options.isInteractive ? await promptDisplayName(name) : displayNameFromProjectName(name));
    const error = validateDisplayName(value);

    return error === undefined ? value.trim() : fail(error);
};

const resolvePackageManager = async (
    requested: PackageManager | undefined,
    options: CreateOptions,
): Promise<PackageManager> => {
    if (requested !== undefined) {
        return requested;
    }

    if (options.isInteractive) {
        return promptPackageManager();
    }

    return (await detectedPackageManager()) ?? "pnpm";
};

const resolveOptions = async (options: CreateOptions): Promise<ResolvedOptions> => {
    const requested = requestedPackageManager(options.packageManager);
    const target = await resolveTarget(options);
    const name = deriveProjectName(target);
    const displayName = await resolveDisplayName(options, name);
    const applicationId = await resolveApplicationId(options, name);
    const root = resolve(process.cwd(), target);
    const isCurrentDirectory = root === process.cwd();
    const shouldInitialize = shouldInitializeGit(root);
    await validateTargetAvailability(root, target, options);
    const packageManager = await resolvePackageManager(requested, options);
    const isTypescript = await isOptionEnabled(options.isTypescript, options.isInteractive, "Use TypeScript?");

    const shouldIncludeTesting = await isOptionEnabled(
        options.shouldIncludeTesting,
        options.isInteractive,
        "Include testing setup (Vitest)?",
    );

    return {
        target,
        root,
        isCurrentDirectory,
        name,
        displayName,
        applicationId,
        packageManager,
        isTypescript,
        shouldIncludeTesting,
        shouldInitializeGit: shouldInitialize,
    };
};

const isTemplateIncluded = (templateRelativePath: string, resolved: ResolvedOptions): boolean => {
    if (TESTING_TEMPLATES.has(templateRelativePath)) {
        return resolved.shouldIncludeTesting;
    }

    if (TYPESCRIPT_TEMPLATES.has(templateRelativePath)) {
        return resolved.isTypescript;
    }

    return true;
};

const destinationPath = (template: string, resolved: ResolvedOptions): string => {
    const scriptPath = resolved.isTypescript ? template : template.replace(/\.tsx$/, ".jsx").replace(/\.ts$/, ".js");

    return scriptPath.endsWith(ICON_TEMPLATE_NAME)
        ? `${scriptPath.slice(0, -ICON_TEMPLATE_NAME.length)}${resolved.applicationId}.svg`
        : scriptPath;
};

const templateContext = (resolved: ResolvedOptions): TemplateContext => ({
    name: resolved.name,
    applicationId: resolved.applicationId,
    displayName: resolved.displayName,
    shouldIncludeTesting: resolved.shouldIncludeTesting,
    isTypescript: resolved.isTypescript,
    importExtension: resolved.isTypescript ? ".js" : ".jsx",
    developerName: gitConfigValue("user.name") ?? resolved.displayName,
    developerEmail: gitConfigValue("user.email"),
});

const replaceTemplateDestination = (destination: string): void => {
    const entry = lstatSync(destination, { throwIfNoEntry: false });

    if (entry === undefined) {
        return;
    }

    if (!entry.isFile() && !entry.isSymbolicLink()) {
        fail(`Cannot replace scaffold file because its destination is not a file: ${destination}`);
    }

    rmSync(destination, { force: true });
};

const projectRelativeDestination = (root: string, destination: string): string => {
    const relativePath = relative(root, destination);
    const isOutsideProject = relativePath.length === 0 || relativePath.startsWith(`..${sep}`) ||
        isAbsolute(relativePath);

    if (isOutsideProject) {
        fail(`Scaffold destination is outside the project: ${destination}`);
    }

    return relativePath;
};

const assertRootIsNotSymbolicLink = (root: string): void => {
    const rootEntry = lstatSync(root, { throwIfNoEntry: false });

    if (rootEntry?.isSymbolicLink()) {
        fail(`Cannot scaffold through a symbolic link: ${root}`);
    }
};

const assertSafeAncestor = (ancestor: string): void => {
    const entry = lstatSync(ancestor, { throwIfNoEntry: false });

    if (entry?.isSymbolicLink()) {
        fail(`Cannot scaffold through a symbolic link: ${ancestor}`);
    }

    if (entry !== undefined && !entry.isDirectory()) {
        fail(`Cannot scaffold through a non-directory path: ${ancestor}`);
    }
};

const assertSafeAncestors = (root: string, relativePath: string): void => {
    let ancestor = root;
    const segments = relativePath.split(sep);
    const ancestorSegments = segments.slice(0, -1);

    for (const segment of ancestorSegments) {
        ancestor = join(ancestor, segment);
        assertSafeAncestor(ancestor);
    }
};

const assertReplaceableDestination = (destination: string): void => {
    const entry = lstatSync(destination, { throwIfNoEntry: false });
    const isReplaceable = entry === undefined || entry.isFile() || entry.isSymbolicLink();

    if (!isReplaceable) {
        fail(`Cannot replace scaffold file because its destination is not a file: ${destination}`);
    }
};

const assertSafeDestination = (root: string, destination: string): void => {
    const relativePath = projectRelativeDestination(root, destination);
    assertRootIsNotSymbolicLink(root);
    assertSafeAncestors(root, relativePath);
    assertReplaceableDestination(destination);
};

const plannedScaffoldFiles = async (root: string, resolved: ResolvedOptions): Promise<ScaffoldFile[]> => {
    const context = templateContext(resolved);
    const files: ScaffoldFile[] = [];

    for (const template of listTemplates()) {
        if (isTemplateIncluded(template, resolved)) {
            files.push({
                destination: join(root, destinationPath(template, resolved)),
                contents: await renderFile(template, context),
            });
        }
    }

    return files;
};

const auxiliaryDestinations = (root: string, resolved: ResolvedOptions): string[] => [
    ...(resolved.packageManager === "pnpm" ? [join(root, "pnpm-workspace.yaml")] : []),
    ...(resolved.isTypescript ? [join(root, "node_modules", ".gtkx", "env.d.ts")] : []),
];

const scaffoldProject = async (root: string, resolved: ResolvedOptions): Promise<void> => {
    const files = await plannedScaffoldFiles(root, resolved);
    const destinations = [...files.map((file) => file.destination), ...auxiliaryDestinations(root, resolved)];

    for (const destination of destinations) {
        assertSafeDestination(root, destination);
    }

    for (const destination of destinations) {
        replaceTemplateDestination(destination);
    }

    for (const file of files) {
        mkdirSync(dirname(file.destination), { recursive: true });
        writeFileSync(file.destination, file.contents);
    }

    if (resolved.shouldIncludeTesting) {
        updateManifest(root, (manifest) => {
            (manifest.scripts as Record<string, string>).test = "vitest run";
        });
    }
};

const withoutInheritedScriptPolicy = async (run: () => Promise<void>): Promise<void> => {
    const saved = INHERITED_SCRIPT_POLICY_VARS.map((key) => [key, process.env[key]] as const);

    for (const [key] of saved) {
        Reflect.deleteProperty(process.env, key);
    }

    try {
        await run();
    } finally {
        for (const [key, value] of saved) {
            if (value !== undefined) {
                process.env[key] = value;
            }
        }
    }
};

const installDependencies = async (options: InstallDependenciesOptions): Promise<void> => {
    const { cwd, packageManager, dependencies, isDev } = options;

    await withoutInheritedScriptPolicy(async () => {
        await addDependency(dependencies, { cwd, packageManager, dev: isDev, silent: true });
    });
};

const pin = (names: string[]): string[] =>
    names.map((dependency) => dependency.startsWith("@gtkx/") ? `${dependency}@^${selfVersion}` : dependency);

const formatRecovery = ({ resolved, devDependencies }: InstallFailureOptions): string => {
    const add = ADD_COMMAND[resolved.packageManager];

    const steps = [
        ...(resolved.isCurrentDirectory ? [] : [`cd ${resolved.target}`]),
        `${add} ${pin(DEPENDENCIES).join(" ")}`,
        `${add} -D ${pin(devDependencies).join(" ")}`,
    ];

    const indented = steps.map((step) => `  ${step}`).join("\n");

    return `${RECOVERY_HEADING}\n${indented}`;
};

const explainInstallFailure = (options: InstallFailureOptions): void => {
    const hint = getInstallHint(errorMessage(options.error));

    if (hint !== undefined) {
        p.log.warn(hint);
    }

    p.log.info(formatRecovery(options));
};

const runWithSpinner = async (step: SpinnerStep): Promise<void> => {
    const spinner = p.spinner();
    spinner.start(step.pending);

    try {
        await step.run();
        spinner.stop(step.done);
    } catch (error) {
        spinner.error(step.failed);
        p.log.error(errorMessage(error));
        step.explain?.(error);
        throw new ScaffoldAbortedError(step.failed);
    }
};

const installAllDependencies = async (options: InstallAllOptions): Promise<void> => {
    const { resolved, devDependencies } = options;
    const { root, packageManager } = resolved;

    await runWithSpinner({
        pending: "Installing dependencies...",
        done: "Dependencies installed",
        failed: "Failed to install dependencies",
        run: async () => {
            await installDependencies({ cwd: root, packageManager, dependencies: pin(DEPENDENCIES), isDev: false });
            await installDependencies({ cwd: root, packageManager, dependencies: pin(devDependencies), isDev: true });
        },
        explain: (error) => {
            explainInstallFailure({ error, resolved, devDependencies });
        },
    });
};

const writeInitialEnvModule = (root: string): void => {
    const storeDir = join(root, "node_modules", ".gtkx");
    mkdirSync(storeDir, { recursive: true });
    writeFileSync(join(storeDir, "env.d.ts"), `${GTKX_ENV_MODULE_HEADER}\n`);
};

const isInsideGitRepository = (root: string): boolean => {
    const git = tryResolveExecutable("git");

    if (git === undefined) {
        return false;
    }

    try {
        execFileSync(git, ["-C", root, "rev-parse", "--show-toplevel"], { stdio: "ignore" });

        return true;
    } catch {
        return false;
    }
};

const initializeGitRepo = async (root: string, shouldInitialize: boolean): Promise<void> => {
    if (!shouldInitialize || isInsideGitRepository(root)) {
        return;
    }

    const spinner = p.spinner();
    spinner.start("Initializing git repository...");

    try {
        const opts = { nodeOptions: { cwd: root }, throwOnError: true } as const;
        await x("git", ["init"], opts);
        await x("git", ["add", "-A"], opts);
        await x("git", ["commit", "-m", "Initial commit"], opts);
        spinner.stop("Git repository initialized");
    } catch {
        spinner.error("Failed to initialize git repository");
    }
};

const printNextSteps = (resolved: ResolvedOptions): void => {
    const devCmd = DEV_COMMAND[resolved.packageManager];
    const cdStep = resolved.isCurrentDirectory ? "" : `cd ${resolved.target}\n`;
    const testingNote = resolved.shouldIncludeTesting ? HEADLESS_COMPOSITOR_NOTE : "";
    p.note(`${cdStep}${devCmd}${testingNote}`, "Next steps");
};

const createProjectStructure = async (root: string, resolved: ResolvedOptions): Promise<void> => {
    await runWithSpinner({
        pending: "Creating project structure...",
        done: "Project structure created",
        failed: "Failed to create the project structure",
        run: async () => {
            mkdirSync(root, { recursive: true });
            await scaffoldProject(root, resolved);
            writeBuildAllowance(root, resolved.packageManager);

            if (resolved.isTypescript) {
                writeInitialEnvModule(root);
            }
        },
    });
};

const scaffold = async (options: CreateOptions = {}): Promise<void> => {
    p.intro("Create GTKX App");
    const resolved = await resolveOptions(options);
    const { root } = resolved;
    const devDeps = getDevDependencies(resolved);
    await createProjectStructure(root, resolved);
    await installAllDependencies({ resolved, devDependencies: devDeps });

    await initializeGitRepo(root, resolved.shouldInitializeGit);
    printNextSteps(resolved);
};

export { scaffold };
