import { describe, expect, it } from "vitest";
import { parseSchemaXml } from "../../src/gsettings/parser.js";
import { renderEnvModule, renderRuntimeModule } from "../../src/gsettings/render.js";

const parse = (xml: string, fileName = "test.gschema.xml") => parseSchemaXml(xml, fileName);

const FIXED_SCHEMA = `<schemalist>
    <schema id="com.example.app" path="/com/example/app/">
        <key name="enabled" type="b"><default>false</default></key>
        <key name="size" type="(ii)"><default>(1, 2)</default></key>
    </schema>
</schemalist>`;

const RELOCATABLE_SCHEMA = `<schemalist>
    <schema id="com.example.profile">
        <key name="title" type="s"><default>''</default></key>
    </schema>
</schemalist>`;

const ENUM_SCHEMA = `<schemalist>
    <enum id="com.example.Mode">
        <value nick="auto" value="0"/>
        <value nick="manual" value="1"/>
    </enum>
    <flags id="com.example.Sides">
        <value nick="left" value="1"/>
        <value nick="right" value="2"/>
    </flags>
    <schema id="com.example.app" path="/com/example/app/">
        <key name="mode" enum="com.example.Mode"><default>'auto'</default></key>
        <key name="sides" flags="com.example.Sides"><default>[]</default></key>
        <key name="style" type="s">
            <choices><choice value="light"/><choice value="dark"/></choices>
            <default>'light'</default>
        </key>
        <key name="ratio" type="d"><default>1.0</default><summary>Ratio</summary></key>
    </schema>
</schemalist>`;

describe("renderRuntimeModule", () => {
    it("renders fixed-path schemas as refs with a null path and a default export", () => {
        const code = renderRuntimeModule(parse(FIXED_SCHEMA));

        expect(code).toContain(`const keys_0 = { "enabled": "b", "size": "(ii)" };`);
        expect(code).toContain(`export const com_example_app = { id: "com.example.app", path: null, keys: keys_0 };`);
        expect(code).toContain("export default com_example_app;");
    });

    it("renders relocatable schemas with an at(path) binder", () => {
        const code = renderRuntimeModule(parse(RELOCATABLE_SCHEMA));

        expect(code).toContain(
            `export const com_example_profile = { id: "com.example.profile", keys: keys_0, at: (path) => ({ id: "com.example.profile", path, keys: keys_0 }) };`,
        );
    });

    it("maps enum and flags keys to their dispatch kinds", () => {
        const code = renderRuntimeModule(parse(ENUM_SCHEMA));

        expect(code).toContain(`"mode": "enum"`);
        expect(code).toContain(`"sides": "flags"`);
        expect(code).toContain(`"style": "s"`);
    });

    it("escapes line separators when embedding strings into generated code", () => {
        const keyName = "line\u2028sep\u2029key";
        const xml = `<schemalist>
    <schema id="com.example.app" path="/com/example/app/">
        <key name="${keyName}" type="s"><default>''</default></key>
    </schema>
</schemalist>`;

        const code = renderRuntimeModule(parse(xml));

        expect(code).toContain(String.raw`"line\u2028sep\u2029key"`);
        expect(code).not.toContain("\u2028");
        expect(code).not.toContain("\u2029");
    });
});

describe("renderEnvModule (typing)", () => {
    it("declares an ambient module per file, keyed on the exact #data specifier", () => {
        const env = renderEnvModule([parse(FIXED_SCHEMA, "#data/com.example.app.gschema.xml")]);

        expect(env).toContain(`declare module "#data/com.example.app.gschema.xml" {`);
        expect(env).toContain("export { com_example_app };");
        expect(env).toContain("export default com_example_app;");
    });

    it("maps scalar GVariant types to native TypeScript types and tuples to GLib.Variant", () => {
        const env = renderEnvModule([parse(FIXED_SCHEMA, "com.example.app.gschema.xml")]);

        expect(env).toContain(`"enabled": boolean;`);
        expect(env).toContain(`"size": import("@gtkx/gi/glib").Variant;`);
    });

    it("narrows enum, flags, and choice keys to unions and emits summaries as JSDoc", () => {
        const env = renderEnvModule([parse(ENUM_SCHEMA, "com.example.app.gschema.xml")]);

        expect(env).toContain(`"mode": "auto" | "manual";`);
        expect(env).toContain(`"sides": ("left" | "right")[];`);
        expect(env).toContain(`"style": "light" | "dark";`);
        expect(env).toContain("/** Ratio */");
        expect(env).toContain(`"ratio": number;`);
    });

    it("declares an at(path) binder for relocatable schemas", () => {
        const env = renderEnvModule([parse(RELOCATABLE_SCHEMA, "com.example.profile.gschema.xml")]);

        expect(env).toContain("at(path: string): {");
        expect(env).not.toContain(`path: string | null;\n        keys`);
    });
});

describe("renderEnvModule (edge cases)", () => {
    it("renders only the header for an empty project", () => {
        const env = renderEnvModule([]);

        expect(env).toContain("GSettings schema modules generated by GTKX");
        expect(env).not.toContain("declare module");
    });

    it("skips files whose schema list is empty", () => {
        const env = renderEnvModule([parse("<schemalist></schemalist>", "empty.gschema.xml")]);

        expect(env).not.toContain("declare module");
    });

    it("disambiguates key type names that normalize to the same identifier", () => {
        const first = parse(
            `<schemalist><schema id="com.example.app" path="/a/"><key name="x" type="b"><default>false</default></key></schema></schemalist>`,
            "a.gschema.xml",
        );
        const second = parse(
            `<schemalist><schema id="com.example-app" path="/b/"><key name="y" type="b"><default>false</default></key></schema></schemalist>`,
            "b.gschema.xml",
        );

        const env = renderEnvModule([first, second]);

        expect(env).toContain("type ComExampleAppKeys = {");
        expect(env).toContain("type ComExampleAppKeys2 = {");
    });
});
