import type { ExternalObject, Handle, Ref } from "@gtkx/native";
import * as GIMarshallingTests from "@gtkx/gi/gimarshallingtests";
import { Value } from "@gtkx/gi/gobject";
import { getHandle, t } from "@gtkx/runtime";
import { resolveExecutable } from "@gtkx/utils";
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, expect, test } from "vitest";
import { drainAfterEachTest } from "./helpers/memory.js";

drainAfterEachTest();

const contents = [0, 49, 255, 51];
const temporary = mkdtempSync(join(tmpdir(), "gtkx-byte-array-values-"));
const library = join(temporary, "libgtkx-byte-array-values.so");
const byteArray = t.byteArray();
const ownedByteArray = t.byteArray("full");
const offsetView = (): Uint8Array => new Uint8Array([99, ...contents, 99]).subarray(1, 5);
const sources = (): (number[] | Uint8Array | Uint8ClampedArray)[] => [
    contents,
    offsetView(),
    Buffer.from([99, ...contents, 99]).subarray(1, 5),
    new Uint8ClampedArray([99, ...contents, 99]).subarray(1, 5),
];

beforeAll(() => {
    const flags = execFileSync(resolveExecutable("pkg-config"), ["--cflags", "--libs", "gio-2.0"], {
        encoding: "utf8",
    }).trim().split(/\s+/);
    execFileSync(resolveExecutable("cc"), [
        "-shared", "-fPIC", "-Wall", "-Wextra", "-Werror",
        join(import.meta.dirname, "fixtures/byte-array-values.c"), "-o", library, ...flags,
    ]);
});

afterAll(() => {
    rmSync(temporary, { recursive: true, force: true });
});

test("generated byte-array bindings accept plain arrays and offset byte views", () => {
    GIMarshallingTests.bytearrayNoneIn(contents);
    GIMarshallingTests.bytearrayNoneIn(offsetView());
    expect(GIMarshallingTests.bytearrayFullReturn()).toEqual(Uint8Array.from(contents));
    expect(GIMarshallingTests.bytearrayFullOut()).toEqual(Uint8Array.from(contents));
});

test.each(["borrowed", "full"] as const)("byte-array inputs retain their bytes with %s transfer", (ownership) => {
    const copy = t.bind(library, ownership === "full" ? "gtkx_byte_array_take" : "gtkx_byte_array_copy", [
        t.byteArray(ownership),
    ], ownedByteArray);

    for (const input of sources()) {
        expect(copy(input)).toEqual(Uint8Array.from(contents));
        expect([...input]).toEqual(contents);
    }
});

test.each([
    { isBytes: false, shouldPreserveNull: false },
    { isBytes: false, shouldPreserveNull: true },
    { isBytes: true, shouldPreserveNull: false },
    { isBytes: true, shouldPreserveNull: true },
])("byte-array results and outputs select their public shape (%o)", ({ isBytes, shouldPreserveNull }) => {
    const descriptor = { ...t.array(t.uint8, "gbytearray", "full", { isBytes }), preserveNull: shouldPreserveNull };
    const read = t.bind(library, "gtkx_byte_array_result", [t.int32], descriptor);
    const out = t.bind(library, "gtkx_byte_array_out", [t.int32, t.ref(descriptor)], t.void);
    const empty = isBytes ? new Uint8Array() : [];
    const populated = isBytes ? Uint8Array.from(contents) : contents;
    const expected = [shouldPreserveNull ? null : empty, empty, populated];

    for (const [state, value] of expected.entries()) {
        expect(read(state)).toEqual(value);
        const output = { value: null };
        out(state, output);
        expect(output.value).toEqual(value);
    }
});

test("byte-array inputs reject invalid elements and incompatible views", () => {
    const copy = t.bind(library, "gtkx_byte_array_copy", [byteArray], ownedByteArray);
    const invalid = [[-1], [256], [0.5], [NaN], [Infinity], ["1"], [undefined], [true],
        new Uint16Array(), new Int8Array([1]), new DataView(new ArrayBuffer(1)), {}, "bytes"];

    for (const input of invalid) {
        expect(() => copy(input)).toThrow();
    }
});

test("inout byte-array refs seed native storage and preserve empty seeds", () => {
    const seeded = t.bind(library, "gtkx_byte_array_seed", [
        t.ref({ ...byteArray, preserveNull: true }, true),
    ], t.int32);

    for (const input of sources()) {
        const ref = { value: input };
        expect(seeded(ref)).toBe(1);
        expect(ref.value).toEqual(Uint8Array.from([...contents, 9]));
        expect([...input]).toEqual(contents);
    }
    for (const value of [null, [], new Uint8Array()]) {
        const ref = { value };
        expect(seeded(ref)).toBe(0);
        expect(ref.value).toBeNull();
    }
    expect(() => seeded({ value: new Uint16Array() })).toThrow();
});

test.each([false, true])("callback byte-array arguments preserve null and empty values (%s)", (preserveNull) => {
    const visit = t.bind(library, "gtkx_byte_array_visit", [
        t.int32, t.callback([{ ...byteArray, preserveNull }], t.void, { scope: "call" }),
    ], t.void);
    const seen: unknown[] = [];

    for (const state of [0, 1, 2]) {
        visit(state, (value: unknown) => {
            seen.push(value);
        });
    }

    expect(seen).toEqual([preserveNull ? null : new Uint8Array(), new Uint8Array(), Uint8Array.from(contents)]);
});

test.each(["borrowed", "full"] as const)("callback byte-array returns honor %s transfer", (ownership) => {
    const invoke = t.bind(library,
        ownership === "full" ? "gtkx_byte_array_callback_return" : "gtkx_byte_array_callback_copy", [
            t.callback([], t.byteArray(ownership), { scope: "call" }),
        ], { ...ownedByteArray, preserveNull: true });

    for (const source of sources()) {
        expect(invoke(() => source)).toEqual(Uint8Array.from(contents));
    }
    expect(invoke(() => [])).toEqual(new Uint8Array());
    expect(invoke(() => new Uint8Array())).toEqual(new Uint8Array());
    expect(invoke(() => null)).toBeNull();
    expect(() => invoke(() => [256])).toThrow();
});

test.each([false, true])("callback byte-array refs write outputs and seed inout values (%s)", (inout) => {
    const descriptor = { ...ownedByteArray, preserveNull: true };
    const invoke = t.bind(library, "gtkx_byte_array_callback_ref", [
        t.int32, t.callback([t.ref(descriptor, inout)], t.void, { scope: "call" }),
    ], descriptor);
    const seen: unknown[] = [];

    const states = inout ? [0, 1, 2, 3] : [0, 3];
    for (const state of states) {
        const result = invoke(state, (ref: Ref) => {
            seen.push(ref.value);
            ref.value = offsetView();
        });
        expect(result).toEqual(state === 3 ? null : Uint8Array.from(contents));
    }

    expect(seen).toEqual(inout ? [null, new Uint8Array(), Uint8Array.from(contents), null] : [null, null]);
    expect(() => invoke(0, (ref: Ref) => {
        ref.value = [-1];
    })).toThrow();
});

test("GValue byte arrays retain independent copied output", () => {
    const getType = t.bind("libgobject-2.0.so.0", "g_byte_array_get_type", [], t.biguint64);
    const value = new Value();
    value.init(getType() as bigint);

    try {
        value.setBoxed(offsetView());
        const bytes = value.getBoxed();
        const items = t.bind("libgobject-2.0.so.0", "g_value_get_boxed", [t.struct()],
            t.array(t.uint8, "gbytearray"))(getHandle(value));
        const duplicate = t.bind("libgobject-2.0.so.0", "g_value_dup_boxed", [t.struct()], ownedByteArray);
        const copied = duplicate(getHandle(value));
        value.setBoxed([9]);

        expect(bytes).toEqual(Uint8Array.from(contents));
        expect(items).toEqual(contents);
        expect(copied).toEqual(Uint8Array.from(contents));
        expect(value.getBoxed()).toEqual(new Uint8Array([9]));
        expect(() => {
            value.setBoxed([256]);
        }).toThrow();
    } finally {
        value.unset();
    }
});

test("byte-array fields write owned containers and read borrowed bytes", () => {
    const create = t.bind(library, "gtkx_byte_array_record_new", [], t.struct());
    const free = t.bind(library, "gtkx_byte_array_record_free", [t.struct()], t.void);
    const record = create() as ExternalObject<Handle>;
    const owned = t.field(ownedByteArray, 0);
    const borrowed = t.field(byteArray, 0);

    try {
        owned.write(record, offsetView());
        expect(borrowed.read(record)).toEqual(Uint8Array.from(contents));
        owned.write(record, [9]);
        expect(borrowed.read(record)).toEqual(new Uint8Array([9]));
        expect(() => {
            owned.write(record, [256]);
        }).toThrow();
        expect(() => {
            borrowed.write(record, [1]);
        }).toThrow();
    } finally {
        free(record);
    }
});

test("async byte-array arguments retain the bytes captured at invocation", async () => {
    const start = t.bind(library, "gtkx_byte_array_async", [
        byteArray,
        t.callback([t.object(), t.object(), t.uint64], t.void, {
            hasUserData: true, userDataIndex: 2, scope: "async",
        }),
    ], t.void);
    const finish = t.bind(library, "gtkx_byte_array_finish", [t.object()], ownedByteArray);
    const input = offsetView();
    const completed = new Promise((resolve) => {
        start(input, (_source: unknown, result: unknown) => {
            resolve(finish(result));
        });
    });

    input.fill(9);

    expect(await completed).toEqual(Uint8Array.from(contents));
});
