import { MINIMUM_NODE_VERSION } from "@gtkx/config/internal";
import { spawnSync } from "node:child_process";
import { chmodSync, copyFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { createCliProject, runCliOrThrow } from "./cli-project.js";

const APPLICATION_ID = "com.gtkx.clilauncher";
const BINARY_NAME = "gtkx-launcher-probe";
const LITERAL_VALUE = "space ' $HOME `echo untouched`";
const NODE_FLAGS = ["--trace-warnings", "--title=two words"];

const deployConfig = (launcher: string): string => `export default {
    applicationId: "${APPLICATION_ID}",
    applicationIcon: "application.svg",
    codegen: false,
    deploy: {
        name: "Launcher Probe",
        developer: { name: "GTKX" },
        binaryName: "${BINARY_NAME}",
        summary: "Exercises the generated launcher",
        description: ["An integration probe for the launcher generated by GTKX."],
        categories: ["Utility"],
        license: "MPL-2.0",
        metadataLicense: "CC0-1.0",
        ${launcher}
    },
};
`;

const files = (): Record<string, string> => ({
    "application.svg": '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"/>\n',
    [join("src", "index.ts")]: `process.stdout.write(JSON.stringify({
        literal: process.env.PROBE_LITERAL,
        threads: process.env.UV_THREADPOOL_SIZE,
        flags: process.execArgv,
        args: process.argv.slice(1),
    }));\n`,
});

const createLauncherProject = (config: string) => createCliProject({
    prefix: "gtkx-deploy-launcher-",
    config,
    files: files(),
    hasStore: true,
});

describe("gtkx deploy (generated launcher)", () => {
    it("passes literal environment values, Node flags, the bundle, and application arguments", () => {
        using project = createLauncherProject(deployConfig(
            `launcherEnv: { PROBE_LITERAL: ${JSON.stringify(LITERAL_VALUE)}, UV_THREADPOOL_SIZE: "16" },
        nodeFlags: ${JSON.stringify(NODE_FLAGS)},`,
        ));

        runCliOrThrow(project, ["deploy", "--print-manifests", "--target", "deb"]);
        const stage = join(project.root, "build", process.arch, "stage");
        const node = join(stage, "lib", BINARY_NAME, "node");
        const launcher = join(stage, "bin", BINARY_NAME);
        copyFileSync(process.execPath, node);
        chmodSync(node, 0o755);

        const run = spawnSync(launcher, ["from user"], {
            cwd: stage,
            encoding: "utf8",
            env: { ...process.env, HOME: "/runtime-home" },
        });

        expect(run.status).toBe(0);
        expect(JSON.parse(run.stdout)).toEqual({
            literal: LITERAL_VALUE,
            threads: "16",
            flags: NODE_FLAGS,
            args: [join(stage, "lib", BINARY_NAME, "bundle.mjs"), "from user"],
        });
        expect(
            readFileSync(
                join(project.root, "build", process.arch, "overlay", "deb", "share", "doc", BINARY_NAME, "copyright"),
                "utf8",
            ),
        ).toContain(`Node.js ${MINIMUM_NODE_VERSION}`);
    });

    it.each([
        'launcherEnv: { "BAD-NAME": "value" },',
        'nodeFlags: ["script.mjs"],',
    ])("rejects unsafe launcher configuration", (launcher) => {
        using project = createLauncherProject(deployConfig(launcher));

        expect(() => runCliOrThrow(project, ["deploy", "--print-manifests", "--target", "deb"])).toThrow();
    });
});
